# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing
__all__ = [
    "Cell",
    "Coords",
    "Element",
    "ElementField",
    "Evolution",
    "FiniteElementSpace",
    "Matrix",
    "Mesh",
    "Model",
    "Node",
    "NodeField",
    "SubElementField",
    "SubEvolution",
    "SubFiniteElementSpace",
    "SubMatrix",
    "SubMesh",
    "SubModel",
    "SubNodeField",
    "abs",
    "barycenter",
    "beam_deformation",
    "circle_seg2",
    "consolidate",
    "contour",
    "coordinates",
    "cos",
    "cosh",
    "deformation",
    "displace",
    "divergence",
    "exp",
    "extrude",
    "fill_surface",
    "flux",
    "from_live_nodes",
    "gradient",
    "integrate_behavior",
    "line_seg2",
    "log",
    "log10",
    "mass",
    "material_field",
    "material_field_per_sub_model",
    "merge",
    "merge_nodes",
    "poi1_from_nodes",
    "restrict",
    "select",
    "set_coordinates",
    "set_swap_dir",
    "sin",
    "sinh",
    "solve",
    "sqrt",
    "stiffness",
    "sub_material_field",
    "surface",
    "swap_dir",
    "sweep_qua4",
    "tan",
    "tanh",
    "to_poi1",
    "volume",
]

@typing.final
class Cell:
    r"""
    One cell of a mesh — the ordered nodes of a single element.
    
    A read-only view obtained by indexing a submesh (`submesh[i]`) or via
    `mesh.cell(submesh, cell)`. `len(cell)` is its node count; iterating a
    cell yields its `Node`s.
    """
    @property
    def index(self) -> builtins.int:
        r"""
        Index of this cell within its submesh.
        """
    @property
    def element_type(self) -> builtins.str:
        r"""
        Element type name of this cell (e.g. `"TRI3"`).
        """
    def nodes(self) -> builtins.list[Node]:
        r"""
        Materialised nodes (each one refcounted on the
        Coords).
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int) -> Node:
        r"""
        `cell[j]` — j-th node of the cell. Supports negative indices
        and raises `IndexError` out of range so `for node in cell:` works.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout: values /
        topology, beyond `repr`'s bounded structure. Returns nothing.
        """

@typing.final
class Coords:
    r"""
    The registry of live nodes and their coordinates, in a fixed spatial
    dimension.
    
    Create one with `Coords(dim)`, then add nodes with
    `add_node([x, y, ...])`. Every mesh, node and field is attached to a
    `Coords`.
    """
    @property
    def dim(self) -> builtins.int:
        r"""
        Spatial dimension of the coordinates (1, 2 or 3).
        """
    @property
    def active(self) -> builtins.int:
        r"""
        Index of the active configuration.
        """
    def __new__(cls, dim: builtins.int) -> Coords:
        r"""
        `Coords(dim)` — an empty `Coords` in `dim` dimensions.
        """
    def node_count(self) -> builtins.int:
        r"""
        Number of live nodes.
        """
    def capacity(self) -> builtins.int:
        r"""
        Number of allocated node slots (live plus not-yet-collected).
        """
    def is_alive(self, id: builtins.int) -> builtins.bool:
        r"""
        Whether node `id` is still live (not garbage-collected).
        
        Takes a **raw id**, not a `Node`, on purpose: a `Node` holds a
        refcount, so it could never be observed dead. This is the API for
        inspecting nodes you may no longer hold (post-GC checks).
        """
    def add_node(self, coords: typing.Sequence[builtins.float]) -> Node:
        r"""
        Add a node at `coords` and return it as a `Node` (refcount = 1).
        """
    def acquire(self, id: builtins.int) -> Node:
        r"""
        Return an additional `Node` for an existing id (refcount += 1).
        """
    def refcount(self, id: builtins.int) -> builtins.int:
        r"""
        Reference count of node `id` (how many holders keep it alive).
        
        Takes a **raw id** (see [`Self::is_alive`]): observing a refcount of
        0 is impossible while holding the `Node` that would carry it.
        """
    def gc(self) -> builtins.int:
        r"""
        Run the garbage collector; return the number of collected nodes.
        """
    def add_config(self, name: builtins.str) -> builtins.int:
        r"""
        Add a named alternative configuration (same nodes, new coordinates);
        returns its index.
        """
    def select(self, config: builtins.int) -> None:
        r"""
        Make configuration `config` the active one.
        """
    def names(self) -> builtins.list[builtins.str]:
        r"""
        Names of the configurations, by index.
        """
    def permutation(self) -> typing.Optional[builtins.list[builtins.int]]:
        r"""
        Current node permutation (a renumbering), or `None` if unset.
        """
    def set_permutation(self, perm: typing.Sequence[builtins.int]) -> None:
        r"""
        Set a node permutation (a renumbering of the nodes).
        """
    def clear_permutation(self) -> None:
        r"""
        Drop any node permutation.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout: values /
        topology, beyond `repr`'s bounded structure. Returns nothing.
        """

@typing.final
class Element:
    r"""
    A single finite element — its geometry together with the interpolation
    and quadrature of its space.
    
    A read-only view obtained by indexing a finite-element subspace
    (`fes[i][j]`); not constructed directly.
    """
    @property
    def index(self) -> builtins.int:
        r"""
        Index of this element within its subspace.
        """
    @property
    def nodes_per_cell(self) -> builtins.int:
        r"""
        Number of nodes of this element.
        """
    @property
    def space_dim(self) -> builtins.int:
        r"""
        Spatial dimension the element lives in.
        """
    @property
    def ref_dim(self) -> builtins.int:
        r"""
        Reference (parametric) dimension of the element.
        """
    @property
    def gauss_count(self) -> builtins.int:
        r"""
        Number of Gauss (quadrature) points.
        """
    def cell(self) -> Cell:
        r"""
        Underlying mesh cell view.
        """
    def nodes(self) -> builtins.list[Node]:
        r"""
        Materialised nodes of this element (each refcounted on the
        Coords) — symmetric with `Cell.nodes()`.
        """
    def gauss_xi(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Reference coordinates of the `g`-th Gauss point.
        """
    def gauss_weight(self, g: builtins.int) -> builtins.float:
        r"""
        Weight of the `g`-th Gauss point.
        """
    def n_at_g(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        `N_i(ξ_g)` at the `g`-th Gauss point (length `nodes_per_cell`).
        """
    def dn_at_g(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        `∂N_i/∂ξ_j(ξ_g)` at the `g`-th Gauss point.
        
        Flat row-major: index `[i * ref_dim + j]`.
        """
    def jacobian(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Jacobian `J = ∂x/∂ξ` at the `g`-th Gauss point.
        """
    def det_jacobian(self, g: builtins.int) -> builtins.float:
        r"""
        `|J|` at the `g`-th Gauss point.
        """
    def dn_dx(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Physical derivatives `∂N_i/∂x_a` at the `g`-th Gauss point.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout: values /
        topology, beyond `repr`'s bounded structure. Returns nothing.
        """

@typing.final
class ElementField:
    r"""
    A field of per-element values (e.g. material properties), one block per
    finite-element zone.
    
    Build with `ElementField(fes, components)` or `material_field(model, ...)`;
    index it (`field[i]`) to reach a `SubElementField`, compose zones
    with `|`.
    """
    def __new__(cls, fespace: FiniteElementSpace, components: typing.Sequence[builtins.str]) -> ElementField:
        r"""
        `ElementField(fespace, components)` — one sub-field per subspace
        of `fespace`, sharing the same `components` list. Zero-initialized.
        """
    @classmethod
    def with_components_per_subspace(cls, fespace: FiniteElementSpace, components_per_subspace: typing.Sequence[typing.Sequence[builtins.str]]) -> ElementField:
        r"""
        Explicit `components` list per subspace.
        """
    def components(self) -> builtins.list[builtins.str]:
        r"""
        Union of the sub-fields' component names, first-seen order.
        """
    def plot(self, view: typing.Optional[tuple[builtins.float, builtins.float, builtins.float]] = None, save: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, show_axes: builtins.bool = True, component: typing.Optional[builtins.str] = None, vmin: typing.Optional[builtins.float] = None, vmax: typing.Optional[builtins.float] = None, cmap: typing.Optional[builtins.str] = None, smooth: builtins.int = 4) -> None:
        r"""
        Visualize this field on its own support: each zone knows its
        submesh through its FE subspace, so the mesh is reconstructed
        (shared, not copied) and coloured by `component` — per-element
        nodal fit of the Gauss values, the discontinuities between
        elements stay visible.
        
        Same `view` / `save` / `show_axes` / `component` / `vmin` /
        `vmax` / `cmap` / `smooth` semantics as `Mesh.plot`.
        """
    def min(self, component: builtins.str) -> builtins.float:
        r"""
        Smallest value of `component` across the sub-fields defining it.
        """
    def max(self, component: builtins.str) -> builtins.float:
        r"""
        Largest value of `component` across the sub-fields defining it.
        """
    def add_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Add `scalar` to `component` on every zone that defines it.
        """
    def sub_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Subtract `scalar` from `component` on every zone that defines it.
        """
    def mul_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Multiply `component` by `scalar` on every zone that defines it.
        """
    def div_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Divide `component` by `scalar` on every zone that defines it.
        """
    def __add__(self, rhs: typing.Any) -> ElementField: ...
    def __sub__(self, rhs: typing.Any) -> ElementField: ...
    def __mul__(self, rhs: typing.Any) -> ElementField: ...
    def __truediv__(self, rhs: typing.Any) -> ElementField: ...
    def __pow__(self, exponent: typing.Any, modulo: typing.Any = None) -> ElementField:
        r"""
        `field ** exponent` — element-wise power, same dispatch as the other
        operators (float → scalar, `ElementField` → strict same-decomposition,
        `SubElementField` → targeted zone). The ternary `pow(x, y, z)` modulo
        form is rejected.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, key: typing.Any) -> typing.Any:
        r"""
        `agg[i]` → the typed **view** of zone `i` (a `$Sub`,
        negative indices supported); `agg[i:j:k]` → a **fresh
        aggregate** of the same type holding the sliced zones
        (Python slicing: step, negative bounds). Other key types
        raise `TypeError`.
        """
    def unit(self) -> SubElementField:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubElementField) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout:
        every sub-object's values/topology, beyond `repr`'s bounded
        structure. Returns nothing.
        """
    def __or__(self, other: typing.Any) -> typing.Any:
        r"""
        `a | b` — **union** of this aggregate with `other`. `other`
        may be another aggregate of the same type or a single
        sub-object. Sub-objects already present (same store slot)
        are not added twice; remaining handles are **shared**
        (refcount bump), not deep-copied. The fields additionally
        fuse zones sharing a support (see their `finalize`), so
        `|` may raise on incoherent values. Returns
        `NotImplemented` for any other type so Python can fall
        back to the right operand's `__ror__`.
        """

@typing.final
class Evolution:
    r"""
    An aggregate of tabulated curves (one `SubEvolution` per zone), interpolated
    linearly against a variable (often time).
    
    Build high-level with `Evolution(steps, out_of_range="error")` where each
    step is `(abscissa, value)` and `value` is a whole `NodeField`,
    `ElementField` or float (whole fields are transposed into one curve per
    zone); or low-level by composing `SubEvolution`s with `|`. Index it
    (`evolution[i]`) to reach a `SubEvolution`.
    """
    def __new__(cls, steps: typing.Sequence[tuple[builtins.float, typing.Any]], out_of_range: builtins.str = 'error') -> Evolution:
        r"""
        `Evolution(steps, out_of_range="error")` — build from whole values
        tabulated at each abscissa. `steps` is a list of `(abscissa, value)`
        where `value` is a float, a `NodeField` or an `ElementField`; the kind
        is taken from the first step. Whole fields are transposed into one
        curve per zone.
        """
    def out_of_range(self) -> builtins.str:
        r"""
        The stored out-of-range policy name.
        """
    def interpolate(self, x: builtins.float, out_of_range: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        Interpolate every curve at `x` and regroup the results: a `list[float]`
        for scalars, a `NodeField` or `ElementField` for fields. `out_of_range`
        overrides the stored policy for this query.
        """
    def plot(self, view: typing.Optional[tuple[builtins.float, builtins.float, builtins.float]] = None, save: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, show_axes: builtins.bool = True, mesh: typing.Optional[Mesh] = None, component: typing.Optional[builtins.str] = None, vmin: typing.Optional[builtins.float] = None, vmax: typing.Optional[builtins.float] = None, cmap: typing.Optional[builtins.str] = None, smooth: builtins.int = 4, frame: typing.Optional[builtins.int] = None, x_label: typing.Optional[builtins.str] = None, y_label: typing.Optional[builtins.str] = None, title: typing.Optional[builtins.str] = None) -> None:
        r"""
        Plot the evolution. A **scalar** evolution draws an X-Y curve (one line
        per zone); a **field** evolution renders like `Mesh.plot(field=...)`
        with a frame slider (drag, or ← / →) picking the tabulated value.
        
        `save` writes a PNG/SVG (a single `frame`, default = last for fields);
        omit it for the interactive window. `mesh` supplies the surface for
        field evolutions (node frames default to a point cloud). `x_label` /
        `y_label` / `title` label the curve.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, key: typing.Any) -> typing.Any:
        r"""
        `agg[i]` → the typed **view** of zone `i` (a `$Sub`,
        negative indices supported); `agg[i:j:k]` → a **fresh
        aggregate** of the same type holding the sliced zones
        (Python slicing: step, negative bounds). Other key types
        raise `TypeError`.
        """
    def unit(self) -> SubEvolution:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubEvolution) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout:
        every sub-object's values/topology, beyond `repr`'s bounded
        structure. Returns nothing.
        """
    def __or__(self, other: typing.Any) -> typing.Any:
        r"""
        `a | b` — **union** of this aggregate with `other`. `other`
        may be another aggregate of the same type or a single
        sub-object. Sub-objects already present (same store slot)
        are not added twice; remaining handles are **shared**
        (refcount bump), not deep-copied. The fields additionally
        fuse zones sharing a support (see their `finalize`), so
        `|` may raise on incoherent values. Returns
        `NotImplemented` for any other type so Python can fall
        back to the right operand's `__ror__`.
        """

@typing.final
class FiniteElementSpace:
    r"""
    The finite-element discretization of a mesh: one subspace per submesh,
    each carrying an interpolation and a quadrature rule.
    
    Build from a `Mesh` with `FiniteElementSpace(mesh)` (or
    `.with_choices(...)` per submesh); index it (`fes[i]`) to reach a
    `SubFiniteElementSpace`, compose several with `|`.
    """
    def __new__(cls, mesh: Mesh, interpolation: builtins.str = 'LAGRANGE1', quadrature: builtins.str = 'GAUSS') -> FiniteElementSpace:
        r"""
        `FiniteElementSpace(mesh)` — Lagrange-1 + default Gauss for
        every submesh.
        
        `FiniteElementSpace(mesh, interpolation="LAGRANGE1", quadrature="GAUSS")`
        — same `(interpolation, quadrature)` applied to every submesh.
        """
    @classmethod
    def with_choices(cls, mesh: Mesh, choices: typing.Sequence[tuple[builtins.str, builtins.str]]) -> FiniteElementSpace:
        r"""
        Explicit `(interpolation, quadrature)` per submesh.
        """
    @classmethod
    def lagrange1(cls, mesh: Mesh) -> FiniteElementSpace:
        r"""
        Convenience: same as `FiniteElementSpace(mesh)`.
        """
    def element(self, sub_idx: builtins.int, cell_idx: builtins.int) -> Element:
        r"""
        `fes.element(sub_idx, cell_idx)` — Element view on a single cell.
        Mirrors `Mesh.cell(sub_idx, cell_idx)`.
        """
    def elements(self, sub_idx: builtins.int) -> builtins.list[Element]:
        r"""
        `fes.elements(sub_idx)` — list of every Element in subspace `sub_idx`.
        Mirrors `Mesh.cells(sub_idx)`.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, key: typing.Any) -> typing.Any:
        r"""
        `agg[i]` → the typed **view** of zone `i` (a `$Sub`,
        negative indices supported); `agg[i:j:k]` → a **fresh
        aggregate** of the same type holding the sliced zones
        (Python slicing: step, negative bounds). Other key types
        raise `TypeError`.
        """
    def unit(self) -> SubFiniteElementSpace:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubFiniteElementSpace) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout:
        every sub-object's values/topology, beyond `repr`'s bounded
        structure. Returns nothing.
        """
    def __or__(self, other: typing.Any) -> typing.Any:
        r"""
        `a | b` — **union** of this aggregate with `other`. `other`
        may be another aggregate of the same type or a single
        sub-object. Sub-objects already present (same store slot)
        are not added twice; remaining handles are **shared**
        (refcount bump), not deep-copied. The fields additionally
        fuse zones sharing a support (see their `finalize`), so
        `|` may raise on incoherent values. Returns
        `NotImplemented` for any other type so Python can fall
        back to the right operand's `__ror__`.
        """

@typing.final
class Matrix:
    r"""
    A global finite-element matrix, assembled from rectangular blocks
    (`SubMatrix`).
    
    Build blocks with `Matrix.block(...)`, compose them with `|`, then call
    `finalize()` before solving. Index it (`matrix[i]`) to reach a block.
    """
    @property
    def symmetric(self) -> builtins.bool:
        r"""
        Whether the matrix is declared symmetric.
        """
    def __new__(cls) -> Matrix:
        r"""
        `Matrix()` — empty aggregate. Populate via `add_sub_matrix`, or
        build blocks with `Matrix.block(...)` and compose them with `|`.
        """
    @classmethod
    def block(cls, row_support: typing.Any, col_support: typing.Any, dual_vars: typing.Sequence[builtins.str], primal_vars: typing.Sequence[builtins.str], ordering: builtins.str = 'nodes_then_vars', symmetric: builtins.bool = False) -> Matrix:
        r"""
        `Matrix.block(row_support, col_support, dual_vars, primal_vars, ordering="nodes_then_vars", symmetric=False)`
        — a single-block `Matrix` (unit aggregate). `row_support` /
        `col_support` may each be a `SubMesh` view or a **unitary** `Mesh`.
        `ordering` is `"nodes_then_vars"` (default) or `"vars_then_nodes"`.
        Fill entries via the block view (`block[0].add_entry(...)`) and
        compose several blocks with `|`, then `finalize()`.
        """
    def finalize(self) -> None:
        r"""
        Build the global DOF table and CSR. Must be called before any
        solver-facing method (`dense`, `mul_dense`, …).
        """
    def n_rows(self) -> builtins.int:
        r"""
        Total number of rows of the (finalized) global matrix.
        """
    def n_cols(self) -> builtins.int:
        r"""
        Total number of columns of the (finalized) global matrix.
        """
    def entry_count(self) -> builtins.int:
        r"""
        Total number of stored entries across all blocks.
        """
    def field_names(self) -> builtins.list[builtins.str]:
        r"""
        Variable (field) names across the whole matrix.
        """
    def row_dofs(self) -> builtins.list[tuple[builtins.int, builtins.str]]:
        r"""
        `(node_id, field_name)` of each global row, in order.
        """
    def col_dofs(self) -> builtins.list[tuple[builtins.int, builtins.str]]:
        r"""
        `(node_id, field_name)` of each global column, in order.
        """
    def get(self, row_node: Node, row_field: builtins.str, col_node: Node, col_field: builtins.str) -> builtins.float:
        r"""
        Value at row `(row_node, row_field)`, column `(col_node, col_field)`.
        """
    def dense(self) -> builtins.list[builtins.float]:
        r"""
        Dense row-major buffer of the finalized matrix (`n_rows × n_cols`).
        """
    def mul_dense(self, x: typing.Sequence[builtins.float]) -> builtins.list[builtins.float]:
        r"""
        `y = A · x` against a dense vector `x`.
        """
    def entries(self) -> builtins.list[tuple[builtins.int, builtins.str, builtins.int, builtins.str, builtins.float]]:
        r"""
        List of `(row_node, row_field, col_node, col_field, value)`
        tuples — every entry across every block, in block-insertion order.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, key: typing.Any) -> typing.Any:
        r"""
        `agg[i]` → the typed **view** of zone `i` (a `$Sub`,
        negative indices supported); `agg[i:j:k]` → a **fresh
        aggregate** of the same type holding the sliced zones
        (Python slicing: step, negative bounds). Other key types
        raise `TypeError`.
        """
    def unit(self) -> SubMatrix:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubMatrix) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout:
        every sub-object's values/topology, beyond `repr`'s bounded
        structure. Returns nothing.
        """
    def __or__(self, other: typing.Any) -> typing.Any:
        r"""
        `a | b` — **union** of this aggregate with `other`. `other`
        may be another aggregate of the same type or a single
        sub-object. Sub-objects already present (same store slot)
        are not added twice; remaining handles are **shared**
        (refcount bump), not deep-copied. The fields additionally
        fuse zones sharing a support (see their `finalize`), so
        `|` may raise on incoherent values. Returns
        `NotImplemented` for any other type so Python can fall
        back to the right operand's `__ror__`.
        """

@typing.final
class Mesh:
    r"""
    A geometric mesh: a collection of submeshes, each holding the cells of a
    single element type.
    
    Build with `Mesh(coords, element_type)` for one zone, compose several
    with `|`; index it (`mesh[i]`) to reach a `SubMesh`.
    """
    def __new__(cls, coords: Coords, element_type: typing.Optional[builtins.str] = None) -> Mesh:
        r"""
        `Mesh(coords)` — empty mesh.
        `Mesh(coords, element_type)` — mesh with one pre-created submesh.
        """
    def element_types(self) -> builtins.list[builtins.str]:
        r"""
        Element type name of each submesh, in order.
        """
    def cell_counts(self) -> builtins.list[builtins.int]:
        r"""
        Number of cells in each submesh, in order.
        """
    def node(self, submesh_idx: builtins.int, cell_idx: builtins.int, node_idx: builtins.int) -> Node:
        r"""
        The `node_idx`-th node of cell `cell_idx` in submesh `submesh_idx`.
        """
    def cell(self, submesh_idx: builtins.int, cell_idx: builtins.int) -> Cell:
        r"""
        `mesh.cell(submesh_idx, cell_idx)` → `Cell` view; same thing
        as `mesh[submesh_idx][cell_idx]`.
        """
    def cell_count(self) -> builtins.int:
        r"""
        Total number of cells across all submeshes.
        """
    def plot(self, view: typing.Optional[tuple[builtins.float, builtins.float, builtins.float]] = None, save: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, show_axes: builtins.bool = True, field: typing.Optional[typing.Any] = None, component: typing.Optional[builtins.str] = None, vmin: typing.Optional[builtins.float] = None, vmax: typing.Optional[builtins.float] = None, cmap: typing.Optional[builtins.str] = None, smooth: builtins.int = 4, wireframe: builtins.bool = False) -> None:
        r"""
        Visualize this mesh (every submesh in its own colour, or
        coloured by a `NodeField` / `ElementField` if `field` is
        supplied). See
        `SubMesh.plot` for the meaning of `view`, `save`, `show_axes`,
        `field`, `component` and `wireframe`.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, key: typing.Any) -> typing.Any:
        r"""
        `agg[i]` → the typed **view** of zone `i` (a `$Sub`,
        negative indices supported); `agg[i:j:k]` → a **fresh
        aggregate** of the same type holding the sliced zones
        (Python slicing: step, negative bounds). Other key types
        raise `TypeError`.
        """
    def unit(self) -> SubMesh:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubMesh) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout:
        every sub-object's values/topology, beyond `repr`'s bounded
        structure. Returns nothing.
        """
    def __or__(self, other: typing.Any) -> typing.Any:
        r"""
        `a | b` — **union** of this aggregate with `other`. `other`
        may be another aggregate of the same type or a single
        sub-object. Sub-objects already present (same store slot)
        are not added twice; remaining handles are **shared**
        (refcount bump), not deep-copied. The fields additionally
        fuse zones sharing a support (see their `finalize`), so
        `|` may raise on incoherent values. Returns
        `NotImplemented` for any other type so Python can fall
        back to the right operand's `__ror__`.
        """

@typing.final
class Model:
    r"""
    A physics problem: a collection of sub-models (heat conduction,
    Dirichlet BCs, ...) over finite-element spaces.
    
    Build sub-models with `Model.heat_conduction(fes)` / `Model.dirichlet(...)`
    and compose them with `|`; assemble with `stiffness` / `mass`.
    """
    def __new__(cls) -> Model:
        r"""
        `Model()` — an empty model; add physics with `|`.
        """
    @classmethod
    def heat_conduction(cls, fespace: FiniteElementSpace) -> Model:
        r"""
        `Model.heat_conduction(fespace)` — heat-conduction model spanning
        **every** subspace of `fespace` (one zone per subspace). A
        single-subspace space gives the unit case; several give one zone
        each. Compose heterogeneous physics with `|`:
        `Model.heat_conduction(fes) | Model.dirichlet(...)`.
        """
    @classmethod
    def truss(cls, fespace: FiniteElementSpace) -> Model:
        r"""
        `Model.truss(fespace)` — truss / bar (axial-force) model spanning
        **every** subspace of `fespace` (SEG2 elements). DOFs are the vector
        displacement `u_x, u_y(, u_z)`; the orientation is taken from the node
        coordinates. Material (`E`, `A`) is supplied at assembly time.
        """
    @classmethod
    def elasticity(cls, fespace: FiniteElementSpace, model: builtins.str) -> Model:
        r"""
        `Model.elasticity(fespace, model)` — linear-elasticity model spanning
        every subspace of `fespace`. `model` is `"plane_stress"` or
        `"plane_strain"` (2-D), or `"solid"` (3-D). DOFs are the vector
        displacement `u_x, u_y(, u_z)`; material (`E`, `nu`) is supplied at
        assembly time.
        """
    @classmethod
    def timoshenko(cls, fespace: FiniteElementSpace) -> Model:
        r"""
        `Model.timoshenko(fespace)` — Timoshenko-beam model spanning every
        subspace of `fespace` (1-D `SEG2`). DOFs `w` (deflection) and `theta`
        (rotation); reduced shear integration avoids locking. Material
        (`E`, `I`, `G`, `A_s`) is supplied at assembly time.
        """
    @classmethod
    def frame(cls, fespace: FiniteElementSpace) -> Model:
        r"""
        `Model.frame(fespace)` — planar frame / portique model spanning every
        subspace of `fespace` (2-D `SEG2`): an oriented Timoshenko beam carrying
        axial + bending + shear. DOFs `u_x, u_y, rz`; material
        (`E`, `A`, `I`, `G`, `A_s`) is supplied at assembly time.
        """
    @classmethod
    def frame3d(cls, fespace: FiniteElementSpace) -> Model:
        r"""
        `Model.frame3d(fespace)` — 3-D Timoshenko frame (space frame) spanning
        every subspace of `fespace` (3-D `SEG2`). 6 DOFs/node: `u_x, u_y, u_z,
        r_x, r_y, r_z`. Section axes are auto-oriented (global-Z reference).
        Material (`E, A, I_y, I_z, J, G, A_sy, A_sz`) is supplied at assembly time.
        """
    @classmethod
    def dirichlet(cls, imposed_variable: builtins.str, target_dual: builtins.str, imposed_mesh: Mesh, multiplier_mesh: Mesh, multiplier: typing.Optional[builtins.str] = None, imposed_value: typing.Optional[builtins.str] = None) -> Model:
        r"""
        `Model.dirichlet(imposed_variable, target_dual, imposed_mesh,
        multiplier_mesh, multiplier=None, imposed_value=None)` — Dirichlet
        constraint model (a single sub-model) imposed via Lagrange multipliers.
        
        `imposed_variable` is the constrained primary variable (e.g. `"T"`);
        `target_dual` is the dual variable of the target physics it couples
        into (e.g. `"q"` for heat conduction). `imposed_mesh` is the POI1 mesh
        of constrained nodes; `multiplier_mesh` is the POI1 support of the
        multipliers (same per-submesh cell count) — usually built from
        `imposed_mesh` with the `barycenter` mesher. `multiplier` /
        `imposed_value` override the derived names `lambda_<imposed_variable>` /
        `imposed_<imposed_variable>`. The imposed value `u_d` is written by the
        user in the load field at the multiplier node's `imposed_value`
        component. See the model chapter of the book for the full semantics.
        """
    def primal_vars(self) -> builtins.list[builtins.str]:
        r"""
        Names of the primal (primary) variables across the whole model.
        """
    def dual_vars(self) -> builtins.list[builtins.str]:
        r"""
        Names of the dual variables across the whole model.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, key: typing.Any) -> typing.Any:
        r"""
        `agg[i]` → the typed **view** of zone `i` (a `$Sub`,
        negative indices supported); `agg[i:j:k]` → a **fresh
        aggregate** of the same type holding the sliced zones
        (Python slicing: step, negative bounds). Other key types
        raise `TypeError`.
        """
    def unit(self) -> SubModel:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubModel) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout:
        every sub-object's values/topology, beyond `repr`'s bounded
        structure. Returns nothing.
        """
    def __or__(self, other: typing.Any) -> typing.Any:
        r"""
        `a | b` — **union** of this aggregate with `other`. `other`
        may be another aggregate of the same type or a single
        sub-object. Sub-objects already present (same store slot)
        are not added twice; remaining handles are **shared**
        (refcount bump), not deep-copied. The fields additionally
        fuse zones sharing a support (see their `finalize`), so
        `|` may raise on incoherent values. Returns
        `NotImplemented` for any other type so Python can fall
        back to the right operand's `__ror__`.
        """

@typing.final
class Node:
    r"""
    A node of a `Coords`: a stable identifier that carries the
    `Coords` it belongs to (and therefore its coordinates).
    
    Created via `Coords.add_node([x, y, ...])`; passed wherever an
    API needs a node.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Stable integer id of this node within its `Coords`.
        """
    def coord(self) -> builtins.list[builtins.float]:
        r"""
        This node's coordinates in the active coordinate set.
        """
    def set_coord(self, coords: typing.Sequence[builtins.float]) -> None:
        r"""
        Overwrite this node's coordinates.
        """
    def __or__(self, other: typing.Any) -> typing.Any:
        r"""
        `node | node` → a unitary POI1 `Mesh` over both nodes (the same
        union `|` as the aggregates). Returns `NotImplemented` for any other
        right-hand type.
        """
    def __ror__(self, other: typing.Any) -> typing.Any:
        r"""
        Right-hand `mesh | node`: append this node to a **unitary POI1**
        `Mesh`, yielding a new one. Reached when the left operand's `__or__`
        returns `NotImplemented` (a `Mesh` doesn't know how to union a `Node`).
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout: values /
        topology, beyond `repr`'s bounded structure. Returns nothing.
        """

@typing.final
class NodeField:
    r"""
    A field of values carried by mesh nodes — one `SubNodeField` block per
    zone, with possibly different components from one zone to the next.
    
    Build with `NodeField(support, components)` where `support` is a `Mesh`
    (one sub-field per submesh) or a single `SubMesh`; index it
    (`field[i]`) to reach a `SubNodeField`, compose zones with `|`. Reads
    (`field.value(node, "T")`) take the first zone defining the pair;
    `field.check()` verifies that zones agree on shared interface nodes.
    """
    def __new__(cls, support: typing.Any, components: typing.Sequence[builtins.str]) -> NodeField:
        r"""
        `NodeField(support, components)` — zero-initialized field. With a
        `Mesh` support: one `SubNodeField` per submesh, each on the
        distinct nodes of its zone. With a `SubMesh`: a single zone.
        """
    @classmethod
    def with_components_per_submesh(cls, mesh: Mesh, components_per_submesh: typing.Sequence[typing.Sequence[builtins.str]]) -> NodeField:
        r"""
        Explicit `components` list per submesh of `mesh`.
        """
    def node_count(self) -> builtins.int:
        r"""
        Number of distinct nodes across the zones.
        """
    def components(self) -> builtins.list[builtins.str]:
        r"""
        Union of the zones' component names, first-seen order.
        """
    def value(self, node: Node, component: builtins.str) -> builtins.float:
        r"""
        Value at `node` for the named `component` — the first zone
        defining both wins. Raises if none does.
        """
    def check(self) -> None:
        r"""
        Verify zone coherence: every `(node, component)` stored by several
        zones must hold the same value everywhere. Raises on the first
        conflict.
        """
    def min(self, component: builtins.str) -> builtins.float:
        r"""
        Smallest value of `component` across the zones defining it.
        """
    def max(self, component: builtins.str) -> builtins.float:
        r"""
        Largest value of `component` across the zones defining it.
        """
    def plot(self, view: typing.Optional[tuple[builtins.float, builtins.float, builtins.float]] = None, save: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, show_axes: builtins.bool = True, component: typing.Optional[builtins.str] = None, vmin: typing.Optional[builtins.float] = None, vmax: typing.Optional[builtins.float] = None, cmap: typing.Optional[builtins.str] = None) -> None:
        r"""
        Visualize this field alone, as a **coloured point cloud** over
        its support nodes — the POI1 support has no connectivity, so no
        surface can be drawn here; use `mesh.plot(field=...)` with the
        original mesh for surfaces.
        
        Same `view` / `save` / `show_axes` / `component` / `vmin` /
        `vmax` / `cmap` semantics as `Mesh.plot`.
        """
    def support_mesh(self) -> Mesh:
        r"""
        A `Mesh` mirroring this field's supports — the zones' POI1
        support submeshes, shared (not copied).
        """
    def add_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Add `scalar` to `component` on every zone that defines it.
        """
    def sub_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Subtract `scalar` from `component` on every zone that defines it.
        """
    def mul_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Multiply `component` by `scalar` on every zone that defines it.
        """
    def div_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Divide `component` by `scalar` on every zone that defines it.
        """
    def __add__(self, rhs: typing.Any) -> NodeField: ...
    def __sub__(self, rhs: typing.Any) -> NodeField: ...
    def __mul__(self, rhs: typing.Any) -> NodeField: ...
    def __truediv__(self, rhs: typing.Any) -> NodeField: ...
    def __pow__(self, exponent: typing.Any, modulo: typing.Any = None) -> NodeField:
        r"""
        `field ** exponent` — element-wise power, same dispatch as the other
        operators (float → scalar, `NodeField` → strict same-decomposition,
        `SubNodeField` → targeted zone). The ternary `pow(x, y, z)` modulo
        form is rejected.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, key: typing.Any) -> typing.Any:
        r"""
        `agg[i]` → the typed **view** of zone `i` (a `$Sub`,
        negative indices supported); `agg[i:j:k]` → a **fresh
        aggregate** of the same type holding the sliced zones
        (Python slicing: step, negative bounds). Other key types
        raise `TypeError`.
        """
    def unit(self) -> SubNodeField:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubNodeField) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout:
        every sub-object's values/topology, beyond `repr`'s bounded
        structure. Returns nothing.
        """
    def __or__(self, other: typing.Any) -> typing.Any:
        r"""
        `a | b` — **union** of this aggregate with `other`. `other`
        may be another aggregate of the same type or a single
        sub-object. Sub-objects already present (same store slot)
        are not added twice; remaining handles are **shared**
        (refcount bump), not deep-copied. The fields additionally
        fuse zones sharing a support (see their `finalize`), so
        `|` may raise on incoherent values. Returns
        `NotImplemented` for any other type so Python can fall
        back to the right operand's `__ror__`.
        """

@typing.final
class SubElementField:
    r"""
    A **view** into one zone of an `ElementField`, obtained by indexing
    (`element_field[i]`) — never constructed directly. Build at the parent
    level instead: `ElementField(fes, components)` or
    `material_field(model, ...)`, composed with `|`.
    """
    def cell_count(self) -> builtins.int:
        r"""
        Number of cells (elements) this field covers.
        """
    def gauss_count(self) -> builtins.int:
        r"""
        Number of Gauss points per cell.
        """
    def component_count(self) -> builtins.int:
        r"""
        Number of components stored per point.
        """
    def components(self) -> builtins.list[builtins.str]:
        r"""
        Component names, in order.
        """
    def component_index(self, name: builtins.str) -> typing.Optional[builtins.int]:
        r"""
        Index of component `name`, or `None` if unknown.
        """
    def get(self, cell: builtins.int, gauss: builtins.int, comp: builtins.int) -> builtins.float:
        r"""
        Value at `(cell, gauss)` for component index `comp`.
        """
    def set(self, cell: builtins.int, gauss: builtins.int, comp: builtins.int, value: builtins.float) -> None:
        r"""
        Set the value at `(cell, gauss)` for component index `comp`.
        """
    def value(self, cell: builtins.int, gauss: builtins.int, component: builtins.str) -> builtins.float:
        r"""
        Value at `(cell, gauss)` for the named `component`.
        """
    def set_value(self, cell: builtins.int, gauss: builtins.int, component: builtins.str, value: builtins.float) -> None:
        r"""
        Set the value at `(cell, gauss)` for the named `component`.
        """
    def point_values(self, cell: builtins.int, gauss: builtins.int) -> builtins.list[builtins.float]:
        r"""
        All component values at `(cell, gauss)`, in component order.
        """
    def set_uniform(self, component: builtins.str, value: builtins.float) -> None:
        r"""
        Set `component` to `value` at every point.
        """
    def set_cell_uniform(self, cell: builtins.int, component: builtins.str, value: builtins.float) -> None:
        r"""
        Set `component` to `value` at every point of `cell`.
        """
    def min(self, component: builtins.str) -> builtins.float:
        r"""
        Smallest value of the named `component`.
        """
    def max(self, component: builtins.str) -> builtins.float:
        r"""
        Largest value of the named `component`.
        """
    def add_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Add `scalar` to every value of `component` (in place).
        """
    def sub_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Subtract `scalar` from every value of `component` (in place).
        """
    def mul_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Multiply every value of `component` by `scalar` (in place).
        """
    def div_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Divide every value of `component` by `scalar` (in place).
        """
    def __add__(self, rhs: typing.Any) -> SubElementField: ...
    def __sub__(self, rhs: typing.Any) -> SubElementField: ...
    def __mul__(self, rhs: typing.Any) -> SubElementField: ...
    def __truediv__(self, rhs: typing.Any) -> SubElementField: ...
    def __pow__(self, exponent: typing.Any, modulo: typing.Any = None) -> SubElementField:
        r"""
        `field ** exponent` — element-wise power, same dispatch as the other
        operators (float exponent → broadcast; `SubElementField` → strict
        element-by-element). The ternary `pow(x, y, z)` modulo form is
        rejected (meaningless on floats).
        """
    def __getitem__(self, key: tuple[builtins.int, builtins.int, builtins.str]) -> builtins.float:
        r"""
        `field[cell, gauss, "name"]` — raises ValueError if the component
        is unknown.
        """
    def __setitem__(self, key: tuple[builtins.int, builtins.int, builtins.str], value: builtins.float) -> None:
        r"""
        `field[cell, gauss, "name"] = value`.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def __or__(self, other: typing.Any) -> typing.Any:
        r"""
        `sub | sub` → a fresh aggregate holding both sub-objects
        (first-seen order, deduplicated by handle, then finalized).
        Sub-handles are shared (refcount bump). Returns
        `NotImplemented` for any other right-hand type.
        """
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout: values /
        topology, beyond `repr`'s bounded structure. Returns nothing.
        """

@typing.final
class SubEvolution:
    r"""
    One tabulated curve: a sorted list of abscissas with the matching values
    (a float, a `SubNodeField` or a `SubElementField`), interpolated linearly.
    
    Build with `SubEvolution(samples, out_of_range="error")` where `samples`
    is a list of `(abscissa, value)` pairs; compose several curves into an
    `Evolution` with `|`.
    """
    def __new__(cls, samples: typing.Sequence[tuple[builtins.float, typing.Any]], out_of_range: builtins.str = 'error') -> SubEvolution:
        r"""
        `SubEvolution(samples, out_of_range="error")` — one curve. `samples`
        is a list of `(abscissa, value)`; the values must all be of the same
        kind (and, for fields, on the same support).
        """
    def __len__(self) -> builtins.int:
        r"""
        Number of samples.
        """
    def abscissas(self) -> builtins.list[builtins.float]:
        r"""
        The sorted abscissas.
        """
    def out_of_range(self) -> builtins.str:
        r"""
        The stored out-of-range policy name.
        """
    def interpolate(self, x: builtins.float, out_of_range: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        Interpolate at `x`. Returns a float, a `SubNodeField` or a
        `SubElementField`. `out_of_range` (`"error"` / `"clamp"` /
        `"extrapolate"`) overrides the stored policy for this query.
        """
    def plot(self, view: typing.Optional[tuple[builtins.float, builtins.float, builtins.float]] = None, save: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, show_axes: builtins.bool = True, mesh: typing.Optional[Mesh] = None, component: typing.Optional[builtins.str] = None, vmin: typing.Optional[builtins.float] = None, vmax: typing.Optional[builtins.float] = None, cmap: typing.Optional[builtins.str] = None, smooth: builtins.int = 4, frame: typing.Optional[builtins.int] = None, x_label: typing.Optional[builtins.str] = None, y_label: typing.Optional[builtins.str] = None, title: typing.Optional[builtins.str] = None) -> None:
        r"""
        Plot this single curve — see `Evolution.plot`. A scalar curve draws an
        X-Y line; a field curve renders with a frame slider.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout: values /
        topology, beyond `repr`'s bounded structure. Returns nothing.
        """
    def __or__(self, other: typing.Any) -> typing.Any:
        r"""
        `sub | sub` → a fresh aggregate holding both sub-objects
        (first-seen order, deduplicated by handle, then finalized).
        Sub-handles are shared (refcount bump). Returns
        `NotImplemented` for any other right-hand type.
        """

@typing.final
class SubFiniteElementSpace:
    r"""
    One subspace of a `FiniteElementSpace`: the finite elements over a
    single submesh, with their interpolation and quadrature.
    
    A read-only view obtained by indexing the parent (`fes[i]`); index it
    further (`fes[i][j]`) to reach an `Element`. Not constructed directly.
    """
    @property
    def element_type(self) -> builtins.str:
        r"""
        Element type name (e.g. `"TRI3"`).
        """
    @property
    def interpolation(self) -> builtins.str:
        r"""
        Interpolation name (e.g. `"LAGRANGE1"`).
        """
    @property
    def quadrature(self) -> builtins.str:
        r"""
        Quadrature-rule name (e.g. `"GAUSS"`).
        """
    @property
    def ref_dim(self) -> builtins.int:
        r"""
        Reference (parametric) dimension of the elements.
        """
    @property
    def space_dim(self) -> builtins.int:
        r"""
        Spatial dimension the elements live in.
        """
    @property
    def nodes_per_cell(self) -> builtins.int:
        r"""
        Number of nodes per element.
        """
    def cell_count(self) -> builtins.int:
        r"""
        Number of elements (cells) in this subspace.
        """
    def gauss_count(self) -> builtins.int:
        r"""
        Number of Gauss (quadrature) points per element.
        """
    def gauss_xi(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Reference coordinates of the `g`-th Gauss point.
        """
    def gauss_weight(self, g: builtins.int) -> builtins.float:
        r"""
        Weight of the `g`-th Gauss point.
        """
    def n_at_g(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        `N_i(ξ_g)` at the `g`-th Gauss point (flat, length `nodes_per_cell`).
        """
    def dn_at_g(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        `∂N_i/∂ξ_j(ξ_g)` at the `g`-th Gauss point.
        
        Flat row-major: index `[i * ref_dim + j]`.
        """
    def jacobian(self, cell_idx: builtins.int, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Jacobian `J = ∂x/∂ξ` of cell `cell_idx` at Gauss point `g`.
        
        Flat row-major buffer of length `space_dim × ref_dim`,
        indexed `[a * ref_dim + k]`.
        """
    def det_jacobian(self, cell_idx: builtins.int, g: builtins.int) -> builtins.float:
        r"""
        `|J|` — `|det(J)|` if `space_dim == ref_dim`, else
        `sqrt(det(JᵀJ))`. Always non-negative.
        """
    def dn_dx(self, cell_idx: builtins.int, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Physical derivatives `∂N_i/∂x_a` of cell `cell_idx` at Gauss
        point `g`. Flat row-major buffer of length
        `nodes_per_cell × space_dim`, indexed `[i * space_dim + a]`.
        """
    def element(self, i: builtins.int) -> Element:
        r"""
        Element view on the `i`-th cell of this subspace.
        """
    def elements(self) -> builtins.list[Element]:
        r"""
        All elements as a Python list.
        """
    def __len__(self) -> builtins.int:
        r"""
        `len(subspace)` → number of elements (= number of cells).
        """
    def __getitem__(self, idx: builtins.int) -> Element:
        r"""
        `subspace[i]` → `Element` view on element `i`. Supports negative
        indices and raises `IndexError` out of range so
        `for el in subspace:` works.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def __or__(self, other: typing.Any) -> typing.Any:
        r"""
        `sub | sub` → a fresh aggregate holding both sub-objects
        (first-seen order, deduplicated by handle, then finalized).
        Sub-handles are shared (refcount bump). Returns
        `NotImplemented` for any other right-hand type.
        """
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout: values /
        topology, beyond `repr`'s bounded structure. Returns nothing.
        """

@typing.final
class SubMatrix:
    r"""
    One block (a COO sub-matrix) of a global `Matrix`, viewed by indexing
    (`matrix[i]`) — never constructed directly. Build a block at the parent
    level with `Matrix.block(...)` (a unit `Matrix`), composed with `|`.
    """
    @property
    def symmetric(self) -> builtins.bool:
        r"""
        Whether this block is declared symmetric.
        """
    def add_entry(self, row_node: Node, row_field: builtins.str, col_node: Node, col_field: builtins.str, value: builtins.float) -> None:
        r"""
        Accumulate `value` at row `(row_node, row_field)`, column
        `(col_node, col_field)` (COO entry).
        """
    def get(self, row_node: Node, row_field: builtins.str, col_node: Node, col_field: builtins.str) -> builtins.float:
        r"""
        Value at row `(row_node, row_field)`, column `(col_node, col_field)`.
        """
    def n_rows(self) -> builtins.int:
        r"""
        Number of rows of this block.
        """
    def n_cols(self) -> builtins.int:
        r"""
        Number of columns of this block.
        """
    def entry_count(self) -> builtins.int:
        r"""
        Number of stored COO entries.
        """
    def field_names(self) -> builtins.list[builtins.str]:
        r"""
        Variable (field) names this block addresses.
        """
    def row_dofs(self) -> builtins.list[tuple[builtins.int, builtins.str]]:
        r"""
        `(node_id, field_name)` tuples for each row, in order.
        """
    def col_dofs(self) -> builtins.list[tuple[builtins.int, builtins.str]]:
        r"""
        `(node_id, field_name)` tuples for each column, in order.
        """
    def dense(self) -> builtins.list[builtins.float]:
        r"""
        Dense row-major buffer, length `n_rows × n_cols`.
        """
    def mul_dense(self, x: typing.Sequence[builtins.float]) -> builtins.list[builtins.float]:
        r"""
        `y = A · x` (dense).
        """
    def entries(self) -> builtins.list[tuple[builtins.int, builtins.str, builtins.int, builtins.str, builtins.float]]:
        r"""
        List of `(row_node, row_field, col_node, col_field, value)`
        tuples, in insertion order.
        """
    def __len__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def __or__(self, other: typing.Any) -> typing.Any:
        r"""
        `sub | sub` → a fresh aggregate holding both sub-objects
        (first-seen order, deduplicated by handle, then finalized).
        Sub-handles are shared (refcount bump). Returns
        `NotImplemented` for any other right-hand type.
        """
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout: values /
        topology, beyond `repr`'s bounded structure. Returns nothing.
        """

@typing.final
class SubMesh:
    r"""
    A **view** into one submesh of a `Mesh` — the cells of a single element
    type. Obtained by indexing (`mesh[i]`); never constructed directly.
    Build at the parent level instead: `Mesh(coords, element_type)` for a
    single zone, composed with `|` for several.
    """
    @property
    def element_type(self) -> builtins.str:
        r"""
        Element type name of this submesh (e.g. `"TRI3"`).
        """
    @property
    def face_color(self) -> tuple[builtins.int, builtins.int, builtins.int]:
        r"""
        Face colour as an `(r, g, b)` tuple of bytes.
        """
    @face_color.setter
    def face_color(self, value: tuple[builtins.int, builtins.int, builtins.int]) -> None:
        r"""
        Set the face colour from an `(r, g, b)` tuple of bytes.
        """
    def add_cell(self, nodes: typing.Sequence[Node]) -> builtins.int:
        r"""
        Append a cell from its list of nodes; returns the new cell's index.
        """
    def cell_count(self) -> builtins.int:
        r"""
        Number of cells in this submesh.
        """
    def plot(self, view: typing.Optional[tuple[builtins.float, builtins.float, builtins.float]] = None, save: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, show_axes: builtins.bool = True, field: typing.Optional[typing.Any] = None, component: typing.Optional[builtins.str] = None, vmin: typing.Optional[builtins.float] = None, vmax: typing.Optional[builtins.float] = None, cmap: typing.Optional[builtins.str] = None, smooth: builtins.int = 4, wireframe: builtins.bool = False) -> None:
        r"""
        Visualize this submesh.
        
        - `save=None`: interactive window (requires `viz-interactive`).
        - `save="<path>.png"` or `.svg`: image file.
        - `view`: optional `(yaw, pitch, scale)` triple; default is iso.
        - `show_axes`: draw the X/Y/Z orientation gizmo in the bottom-left
          corner (default `True`). In the interactive window, the key
          `A` toggles it at runtime.
        - `field`: optional `NodeField` **or** `ElementField` whose values
          colour each cell. Node field: per-cell nodal values read
          directly. Element field: nodal values fitted per element from
          the Gauss values (least squares local to the cell — the
          discontinuities between elements stay visible; with a single
          Gauss point the colour is constant per element).
          Default `None` ⇒ uniform face colour.
        - `component`: component name to display when `field` is set
          (defaults to the field's first component). In the
          interactive window, click the top button or press `Tab` to
          cycle through every component.
        - `vmin` / `vmax`: pin the bottom / top of the colour scale (and
          of the colorbar drawn on the right). Either may be left `None`
          to track the data's own min / max for that bound.
        - `cmap`: colour scale name — `"viridis"` (default), `"jet"`,
          `"coolwarm"`, `"hot"` or `"gray"`.
        - `smooth`: subdivision level of the interpolated rendering
          (default `4`): the colour follows the shape functions inside
          each element. `0` = one flat colour per cell.
        - `wireframe`: when `True`, draw every element edge as a line
          (interior edges of volume cells included) instead of the opaque
          outer skin. Geometry only — combining it with `field` raises
          `ValueError`, since a field always colours the faces.
        """
    def __len__(self) -> builtins.int:
        r"""
        `len(submesh)` → number of cells.
        """
    def __getitem__(self, idx: builtins.int) -> Cell:
        r"""
        `submesh[i]` → `Cell` view on cell i. Supports negative
        indices and raises `IndexError` out of range so
        `for cell in submesh:` works.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def __or__(self, other: typing.Any) -> typing.Any:
        r"""
        `sub | sub` → a fresh aggregate holding both sub-objects
        (first-seen order, deduplicated by handle, then finalized).
        Sub-handles are shared (refcount bump). Returns
        `NotImplemented` for any other right-hand type.
        """
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout: values /
        topology, beyond `repr`'s bounded structure. Returns nothing.
        """

@typing.final
class SubModel:
    r"""
    A **view** into one sub-model of a `Model`, obtained by indexing
    (`model[i]`) — never constructed directly. Build physics at the parent
    level instead: `Model.heat_conduction(fes)` or `Model.dirichlet(...)`,
    composed with `|`.
    """
    def primal_vars(self) -> builtins.list[builtins.str]:
        r"""
        Names of the primal (primary) variables of this sub-model.
        """
    def dual_vars(self) -> builtins.list[builtins.str]:
        r"""
        Names of the dual variables of this sub-model.
        """
    def multiplier_mesh(self) -> Mesh:
        r"""
        POI1 `Mesh` of the multiplier nodes (Lagrange physics only — empty
        otherwise). Build a load `SubNodeField` on `mesh[0]` to impose the
        constrained values, or read the nodes via `mesh.node(0, i, 0)`.
        """
    def material_components(self) -> typing.Optional[builtins.list[builtins.str]]:
        r"""
        Names of the material components this sub-model expects, or
        `None` for physics that don't need material data (Dirichlet, …).
        """
    def has_behavior(self) -> builtins.bool:
        r"""
        Whether this sub-model carries a constitutive behaviour that can be
        integrated with `deformation` / `integrate_behavior` (`True` for
        volumetric physics, `False` for constraints like Dirichlet).
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def __or__(self, other: typing.Any) -> typing.Any:
        r"""
        `sub | sub` → a fresh aggregate holding both sub-objects
        (first-seen order, deduplicated by handle, then finalized).
        Sub-handles are shared (refcount bump). Returns
        `NotImplemented` for any other right-hand type.
        """
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout: values /
        topology, beyond `repr`'s bounded structure. Returns nothing.
        """

@typing.final
class SubNodeField:
    r"""
    A **view** into one zone of a `NodeField`, obtained by indexing
    (`node_field[i]`) — never constructed directly. Build at the parent
    level instead: `NodeField(support, components)`, composed with `|`.
    """
    def node_count(self) -> builtins.int:
        r"""
        Number of nodes in the support.
        """
    def component_count(self) -> builtins.int:
        r"""
        Number of components stored per node.
        """
    def components(self) -> builtins.list[builtins.str]:
        r"""
        Component names, in order.
        """
    def get(self, node_idx: builtins.int, comp_idx: builtins.int) -> builtins.float:
        r"""
        Value at node index `node_idx`, component index `comp_idx`.
        """
    def set(self, node_idx: builtins.int, comp_idx: builtins.int, value: builtins.float) -> None:
        r"""
        Set the value at node index `node_idx`, component index `comp_idx`.
        """
    def get_by_node(self, node: Node, comp_idx: builtins.int) -> builtins.float:
        r"""
        Value at `node`, component index `comp_idx`.
        """
    def set_by_node(self, node: Node, comp_idx: builtins.int, value: builtins.float) -> None:
        r"""
        Set the value at `node`, component index `comp_idx`.
        """
    def component_index(self, name: builtins.str) -> typing.Optional[builtins.int]:
        r"""
        Index of component `name`, or `None` if unknown.
        """
    def node_values(self, node_idx: builtins.int) -> builtins.list[builtins.float]:
        r"""
        All component values at node index `node_idx`, in order.
        """
    def support_submesh(self) -> SubMesh:
        r"""
        The POI1 `SubMesh` this sub-field is supported on.
        """
    def support_mesh(self) -> Mesh:
        r"""
        The POI1 `Mesh` this sub-field is supported on.
        """
    def value(self, node: Node, component: builtins.str) -> builtins.float:
        r"""
        Value at `node` for the named `component`.
        """
    def set_value(self, node: Node, component: builtins.str, value: builtins.float) -> None:
        r"""
        Set the value at `node` for the named `component`.
        """
    def min(self, component: builtins.str) -> builtins.float:
        r"""
        Smallest value of the named `component`.
        """
    def max(self, component: builtins.str) -> builtins.float:
        r"""
        Largest value of the named `component`.
        """
    def add_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Add `scalar` to every value of `component` (in place).
        """
    def sub_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Subtract `scalar` from every value of `component` (in place).
        """
    def mul_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Multiply every value of `component` by `scalar` (in place).
        """
    def div_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Divide every value of `component` by `scalar` (in place).
        """
    def __add__(self, rhs: typing.Any) -> SubNodeField: ...
    def __sub__(self, rhs: typing.Any) -> SubNodeField: ...
    def __mul__(self, rhs: typing.Any) -> SubNodeField: ...
    def __truediv__(self, rhs: typing.Any) -> SubNodeField: ...
    def __pow__(self, exponent: typing.Any, modulo: typing.Any = None) -> SubNodeField:
        r"""
        `field ** exponent` — element-wise power, same dispatch as the other
        operators (float exponent → broadcast; `SubNodeField` → strict
        element-by-element). The ternary `pow(x, y, z)` modulo form is
        rejected (meaningless on floats).
        """
    def __getitem__(self, key: tuple[Node, builtins.str]) -> builtins.float:
        r"""
        `subfield[node, "UX"]` — raises if the node or component is absent.
        """
    def __setitem__(self, key: tuple[Node, builtins.str], value: builtins.float) -> None:
        r"""
        `subfield[node, "UX"] = v` — raises if the node or component is absent.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> None:
        r"""
        Print the full content (third display level) to stdout: values /
        topology, beyond `repr`'s bounded structure. Returns nothing.
        """
    def __or__(self, other: typing.Any) -> typing.Any:
        r"""
        `sub | sub` → a fresh aggregate holding both sub-objects
        (first-seen order, deduplicated by handle, then finalized).
        Sub-handles are shared (refcount bump). Returns
        `NotImplemented` for any other right-hand type.
        """

def abs(field: typing.Any) -> typing.Any:
    r"""
    Element-wise absolute value of a field.
    """

def barycenter(mesh: Mesh) -> Mesh:
    r"""
    Build a POI1 mesh of per-element centroids (centres of gravity), submesh
    by submesh.
    
    Returns a new mesh with the same number of submeshes; each output submesh
    is a POI1 submesh with one **fresh** node per element of the corresponding
    input submesh, placed at the element's centroid. A POI1 input is therefore
    copied to colocated fresh nodes — handy to mint Lagrange-multiplier support
    nodes from a set of constrained points.
    """

def beam_deformation(field: NodeField, fespace: FiniteElementSpace) -> ElementField:
    r"""
    Timoshenko-beam section strains `(kappa, gamma)` of a `(w, theta)` node
    field at the Gauss points of `fespace`. Feed the result to
    `integrate_behavior` of a Timoshenko model to obtain the section forces
    `M = E·I·κ` and `V = G·A_s·γ`.
    """

def circle_seg2(center: Node, normal: typing.Sequence[builtins.float], radius: builtins.float, n_elems: builtins.int) -> Mesh:
    r"""
    Build a closed circle of `n_elems` SEG2 elements, centred on `center`
    in the plane defined by `normal`, with the given `radius`.
    """

def consolidate(obj: typing.Any) -> typing.Any:
    r"""
    Consolidate a container — fuse redundant sub-objects « au plus juste ».
    
    Dispatches on the argument type (Python has a single top-level name
    for the two themed Rust ops):
    
    - `Mesh` → `ops::mesher::consolidate`: fuse submeshes of the same
      element type, drop duplicate cells;
    - `NodeField` → `ops::field::consolidate`: fuse zones with the same
      component set, dedupe interface nodes after a coherence check.
    """

def contour(mesh: Mesh) -> Mesh:
    r"""
    Extract the boundary of a surface mesh (TRI3/QUA4) as closed SEG2 loops.
    
    An element edge used by exactly one cell is a boundary edge; the boundary
    edges (pooled across all surface submeshes) are chained into closed loops.
    Returns a Mesh with one SEG2 submesh per loop — a single loop for a
    simply-connected domain, several when the domain has holes or disjoint
    pieces. Loops keep the CCW boundary orientation (outer loop CCW, holes
    CW), so the result can feed straight back into `surface` / `fill_surface`.
    """

def coordinates(mesh: Mesh, components: typing.Optional[typing.Sequence[builtins.str]] = None) -> NodeField:
    r"""
    Build a `NodeField` carrying the coordinates of every node of `mesh`
    — one `SubNodeField` per submesh, on the distinct nodes of its zone.
    
    One component per requested axis (`"X"`, `"Y"`, `"Z"`). `components=None`
    requests all the axes the mesh's `Coords` has (`["X"]` in 1-D,
    `["X", "Y"]` in 2-D, `["X", "Y", "Z"]` in 3-D).
    """

def cos(field: typing.Any) -> typing.Any:
    r"""
    Element-wise cosine of a field (radians).
    """

def cosh(field: typing.Any) -> typing.Any:
    r"""
    Element-wise hyperbolic cosine of a field.
    """

def deformation(u: NodeField, fespace: FiniteElementSpace) -> ElementField:
    r"""
    Linearized (small-strain) deformation `ε = ½(∇u + ∇uᵀ)` of a displacement
    field `u` at the Gauss points of `fespace`.
    
    `u` must carry exactly `space_dim` components, taken in order as the
    displacement along x, y, z. Returns the symmetric strain tensor
    (`eps_xx`, `eps_xy`, … in tensor convention). The only deformation
    measure for now; non-linear ones will share this shape.
    """

def displace(field: NodeField, components: typing.Optional[typing.Sequence[builtins.str]] = None) -> None:
    r"""
    Displace nodes by `field` (incremental): `coord[a] += field.value(node,
    components[a])` on the active coordinate set. `components` lists one
    displacement-component name per spatial axis, in axis order; `None` →
    `["ux", "uy", "uz"][:dim]`. Mutates the field's `Coords` in place.
    """

def divergence(field: ElementField) -> NodeField:
    r"""
    Weak divergence `div F` of a per-element **vector** field — the adjoint of
    `gradient`: `d_i = ∫ ∇N_i · F dΩ`, accumulated per node. The field must
    carry exactly `space_dim` components (the vector components in order).
    Returns a `NodeField` with a single `"div"` component (one zone per subspace).
    """

def exp(field: typing.Any) -> typing.Any:
    r"""
    Element-wise exponential `eˣ` of a field.
    """

def extrude(mesh: Mesh, direction: typing.Sequence[builtins.float], n_layers: builtins.int) -> Mesh:
    r"""
    Extrude `mesh` by `n_layers` layers along `direction` (the total
    displacement vector). SEG2 → QUA4, QUA4 → HEX8.
    """

def fill_surface(contour: Mesh, element_type: builtins.str, max_edge_length: typing.Optional[builtins.float] = None, min_angle_deg: typing.Optional[builtins.float] = None) -> Mesh:
    r"""
    Fill the interior of a closed SEG2 `contour` with `element_type` cells
    (triangulation). `max_edge_length` / `min_angle_deg` optionally refine
    the result.
    """

def flux(fespace: SubFiniteElementSpace, density: typing.Any, component: builtins.str) -> NodeField:
    r"""
    Consistent nodal loads of a distributed flux over `fespace` — the analogue
    of Cast3m `FLUX` / `PRES`: `∫ density · N_i dΓ`, returned as a `NodeField`
    carrying the single component `component` (the model's dual variable, e.g.
    `"q"` for heat conduction).
    
    `density` is either a **float** (uniform density) or a single-component
    `SubElementField` (per-Gauss density). The element measure comes from the
    FE subspace, so a `SEG2` edge in a 2-D mesh integrates as a line, a surface
    mesh as an area.
    """

def from_live_nodes(coords: Coords) -> Mesh:
    r"""
    Build a points (POI1) mesh holding every live node of `coords`.
    """

def gradient(field: NodeField, fespace: FiniteElementSpace) -> ElementField:
    r"""
    Gradient `∇f` of a node `field` at the Gauss points of `fespace`.
    
    Geometric and physics-agnostic: each component of `field` is
    differentiated w.r.t. every spatial axis, giving an `ElementField` with
    one component `grad_<name>_<axis>` per (input component, axis) pair
    (`grad_T_x`, …). Feed the result to `integrate_behavior`.
    """

def integrate_behavior(model: Model, deformation: ElementField, materials: ElementField) -> ElementField:
    r"""
    Integrate the constitutive law of `model` (Cast3m `COMP`).
    
    `deformation` is the behaviour-input field (from `gradient(field,
    fespace)` or `deformation(u, fespace)`); `materials` supplies the
    per-zone material data. Returns the material-state field (dual
    flux/stress + updated internal variables) of every behaviour-bearing
    sub-model.
    
    For a linear law the result is consistent with the assembled stiffness
    (`∫ Bᵀ·flux = K·u`); a non-linear law is the exact response.
    """

def line_seg2(a: Node, b: Node, n_elems: builtins.int) -> Mesh:
    r"""
    Build a line of `n_elems` SEG2 elements from node `a` to node `b`.
    """

def log(field: typing.Any) -> typing.Any:
    r"""
    Element-wise natural logarithm of a field (`-inf`/`nan` for ≤ 0).
    """

def log10(field: typing.Any) -> typing.Any:
    r"""
    Element-wise base-10 logarithm of a field.
    """

def mass(model: Model) -> Matrix:
    r"""
    Assemble the mass matrix `M` of `model`.
    
    v0 stub: no physics has a mass term yet, so this returns an empty
    finalized `Matrix` with the model's DOF layout.
    """

def material_field(model: Model, components_and_values: typing.Sequence[tuple[builtins.str, builtins.float]]) -> ElementField:
    r"""
    Build a material `ElementField` applying the same uniform
    `(component, value)` pairs to every material-hungry sub-model of
    `model`. Sub-models that need no material (Dirichlet, …) are skipped.
    """

def material_field_per_sub_model(model: Model, components_and_values_per_sub_model: typing.Sequence[typing.Sequence[tuple[builtins.str, builtins.float]]]) -> ElementField:
    r"""
    Build a material `ElementField` where each sub-model gets its own
    `(component, value)` list. The outer list length must equal
    `model.len()`. An empty inner list **skips** the matching
    sub-model (typical for Dirichlet).
    """

def merge(a: NodeField, b: NodeField) -> NodeField:
    r"""
    Merge two node fields « au plus juste »: structural union of their
    zones, consolidated — zones sharing a component set are fused, the
    others stay separate (nothing is densified).
    
    Errors if the two fields hold different values at the same
    `(node, component)` pair, or are attached to different `Coords`s.
    """

def merge_nodes(mesh: Mesh, tol: builtins.float) -> Mesh:
    r"""
    Weld together nodes closer than `tol`, redirecting the connectivity to one
    representative per cluster.
    
    Returns a new mesh mirroring `mesh` (same submeshes, types and colours)
    with welded-away nodes redirected to their cluster representative — the
    smallest-id node of the cluster, which keeps its own coordinates (no
    averaging). Cells that collapse onto a repeated node (a degenerate segment,
    triangle, …) are dropped. `tol` must be ≥ 0; `tol = 0` welds only exactly
    coincident nodes. `mesh` itself is left untouched.
    """

def poi1_from_nodes(nodes: typing.Sequence[Node]) -> Mesh:
    r"""
    Build a points (POI1) mesh with one point per node in `nodes`.
    
    The Coords is taken from the nodes themselves (every `Node`
    carries its own), so no Coords argument is needed. Returns a
    Mesh with a single POI1 submesh; raises if `nodes` is empty.
    """

def restrict(field: NodeField, mesh: Mesh) -> NodeField:
    r"""
    Restrict `field` to the nodes used by `mesh`.
    
    Returns a new `NodeField` with one zone per submesh of `mesh`,
    carrying the union of `field`'s components. Nodes of `mesh` absent
    from `field` are assigned `0.0`. Errors if `mesh` and `field` are
    attached to different `Coords`s.
    """

def select(field: typing.Any, min: typing.Optional[builtins.float] = None, max: typing.Optional[builtins.float] = None, components: typing.Optional[typing.Sequence[builtins.str]] = None) -> Mesh:
    r"""
    Select the part of a field's support whose values fall in `[min, max]`,
    zone by zone — a value-range filter returning a `Mesh`.
    
    `field` may be a `NodeField` / `SubNodeField` (→ POI1 submeshes of the
    passing **nodes**) or an `ElementField` / `SubElementField` (→ submeshes
    of the passing **cells**, each of its zone's element type; a cell passes
    only when *all* its Gauss points do). The result has one submesh per
    processed zone.
    
    At least one of `min` / `max` must be given (inclusive bounds). With
    several components in play the bounds are combined with **AND**: a
    point/cell is kept only when *every* tested component is in band.
    
    `components=None` tests every component of each zone. A `components`
    list tests **only** those components, and only on the zones carrying
    **all** of them — a zone missing any listed component is skipped (no
    submesh). Errors if both bounds are `None`, or `min > max`.
    """

def set_coordinates(field: NodeField, components: typing.Optional[typing.Sequence[builtins.str]] = None) -> None:
    r"""
    Set node coordinates from `field` (absolute): for every node, the
    active-set coordinate on axis `a` becomes `field.value(node,
    components[a])`. `components` lists one component name per spatial axis,
    in axis order; `None` → `["X", "Y", "Z"][:dim]`. Mutates the field's
    `Coords` in place.
    """

def set_swap_dir(path: builtins.str | os.PathLike | pathlib.Path) -> None:
    r"""
    Set the directory used to swap large objects to disk. If never set, a
    per-process subdirectory of the system temp dir is used.
    """

def sin(field: typing.Any) -> typing.Any:
    r"""
    Element-wise sine of a field (radians).
    """

def sinh(field: typing.Any) -> typing.Any:
    r"""
    Element-wise hyperbolic sine of a field.
    """

def solve(matrix: Matrix, rhs: NodeField) -> NodeField:
    r"""
    Solve the linear system `A·x = b` for `x` (dense LU).
    
    `matrix` is the finalized system `A`; `rhs` is the right-hand side `b`
    as a `NodeField` (read through the aggregate, zones resolved per DOF).
    Returns the solution `x` as a single-zone `NodeField` over the
    column-DOF nodes.
    
    A `Ctrl+C` is honoured at the solver's phase boundaries (assembly,
    dense conversion, factorization). The dense factorization itself is a
    single library call and is not interrupted mid-way.
    """

def sqrt(field: typing.Any) -> typing.Any:
    r"""
    Element-wise square root of a field (`nan` for negatives).
    """

def stiffness(model: Model, materials: ElementField) -> Matrix:
    r"""
    Assemble the stiffness matrix `K` of `model`.
    
    `materials` carries the per-zone material data: every sub-model that
    needs it picks the `SubElementField` whose FE subspace matches its own.
    """

def sub_material_field(sub_model: SubModel, components_and_values: typing.Sequence[tuple[builtins.str, builtins.float]]) -> SubElementField:
    r"""
    Build the material `SubElementField` of one sub-model.
    
    `sub_material_field(sub_model, [("k", 1.0), ...])` — fresh
    SubElementField on the sub-model's FE subspace, pre-filled with the
    given uniform value per declared component. Errors for physics that
    need no material (e.g. Dirichlet).
    """

def surface(contour: Mesh, element_type: builtins.str, size: typing.Optional[builtins.float] = None) -> Mesh:
    r"""
    Mesh the interior of a closed SEG2 `contour` with `element_type` cells
    using a size-controlled advancing front that **creates interior nodes**
    (unlike `fill_surface`, which only triangulates the contour nodes).
    
    `size` sets the target element edge length; `None` uses the mean length
    of the contour's segments. `element_type` is "TRI3" or "QUA4" (QUA4 is
    quad-dominant: the result may also carry a few triangles). The contour
    may be 2-D or a nearly planar loop in 3-D (projected, paved, lifted
    back). A single contour is supported for now.
    """

def swap_dir() -> pathlib.Path:
    r"""
    Return the effective swap directory (creating it if necessary).
    """

def sweep_qua4(mesh_a: Mesh, mesh_b: Mesh, n_layers: builtins.int) -> Mesh:
    r"""
    Sweep two SEG2 line meshes into a QUA4 mesh, building `n_layers` layers
    of quads between `mesh_a` and `mesh_b`.
    """

def tan(field: typing.Any) -> typing.Any:
    r"""
    Element-wise tangent of a field (radians).
    """

def tanh(field: typing.Any) -> typing.Any:
    r"""
    Element-wise hyperbolic tangent of a field.
    """

def to_poi1(mesh: Mesh) -> Mesh:
    r"""
    Convert a mesh to POI1, submesh by submesh.
    
    Returns a new mesh with the same number of submeshes; each output
    submesh is a POI1 submesh holding the de-duplicated nodes of the
    corresponding input submesh, in order of first appearance.
    """

def volume(envelope: Mesh, size: typing.Optional[builtins.float] = None) -> Mesh:
    r"""
    Fill the interior of a closed **TRI3** surface `envelope` with TET4 cells
    using a size-controlled **Delaunay** fill that **creates interior nodes** —
    the 3-D companion of `surface`.
    
    `size` sets the target element edge length; `None` uses the mean edge
    length of the envelope's faces. The envelope must be a closed,
    consistently oriented TRI3 surface on a 3-D Coords. The result is a Mesh
    with a single TET4 submesh; boundary nodes are reused. This first version
    targets convex or mildly concave envelopes.
    """

