# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing
__all__ = [
    "Cell",
    "Configuration",
    "Element",
    "ElementField",
    "FiniteElementSpace",
    "Matrix",
    "Mesh",
    "Model",
    "Node",
    "NodeField",
    "SubElementField",
    "SubFiniteElementSpace",
    "SubMatrix",
    "SubMesh",
    "SubModel",
    "circle_seg2",
    "consolidate",
    "coordinates",
    "extrude",
    "fill_surface",
    "from_live_nodes",
    "line_seg2",
    "mass",
    "material_field",
    "material_field_per_sub_model",
    "merge",
    "restrict",
    "set_swap_dir",
    "solve",
    "stiffness",
    "sub_material_field",
    "swap_dir",
    "sweep_qua4",
    "to_poi1",
]

@typing.final
class Cell:
    r"""
    Python wrapper for [`Cell`].
    """
    @property
    def index(self) -> builtins.int: ...
    @property
    def element_type(self) -> builtins.str: ...
    def nodes(self) -> builtins.list[Node]:
        r"""
        Materialised nodes (each one refcounted on the
        Configuration).
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int) -> Node:
        r"""
        `cell[j]` — j-th node of the cell. Supports negative indices
        and raises `IndexError` out of range so `for node in cell:` works.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class Configuration:
    r"""
    Python wrapper for [`Configuration`].
    """
    @property
    def dim(self) -> builtins.int: ...
    @property
    def active_set(self) -> builtins.int: ...
    def __new__(cls, dim: builtins.int) -> Configuration: ...
    def node_count(self) -> builtins.int: ...
    def capacity(self) -> builtins.int: ...
    def is_alive(self, id: builtins.int) -> builtins.bool: ...
    def add_node(self, coords: typing.Sequence[builtins.float]) -> Node:
        r"""
        Add a node and return a [`Node`] (refcount = 1).
        """
    def acquire(self, id: builtins.int) -> Node:
        r"""
        Return an additional [`Node`] for an existing id (refcount += 1).
        """
    def refcount(self, id: builtins.int) -> builtins.int: ...
    def gc(self) -> builtins.int:
        r"""
        Run the garbage collector; return the number of collected nodes.
        """
    def coord(self, id: builtins.int) -> builtins.list[builtins.float]: ...
    def set_coord(self, id: builtins.int, coords: typing.Sequence[builtins.float]) -> None: ...
    def add_coord_set(self, name: builtins.str) -> builtins.int: ...
    def switch_to(self, set: builtins.int) -> None: ...
    def set_names(self) -> builtins.list[builtins.str]: ...
    def permutation(self) -> typing.Optional[builtins.list[builtins.int]]: ...
    def set_permutation(self, perm: typing.Sequence[builtins.int]) -> None: ...
    def clear_permutation(self) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class Element:
    r"""
    Python wrapper for [`Element`] — a thin view on a single element of a
    [`crate::containers::finite_element_space::SubFiniteElementSpace`].
    """
    @property
    def index(self) -> builtins.int: ...
    @property
    def nodes_per_cell(self) -> builtins.int: ...
    @property
    def space_dim(self) -> builtins.int: ...
    @property
    def ref_dim(self) -> builtins.int: ...
    @property
    def gauss_count(self) -> builtins.int: ...
    def cell(self) -> Cell:
        r"""
        Underlying mesh cell view.
        """
    def nodes(self) -> builtins.list[Node]:
        r"""
        Materialised nodes of this element (each refcounted on the
        Configuration) — symmetric with `Cell.nodes()`.
        """
    def gauss_xi(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Reference coordinates of the `g`-th Gauss point.
        """
    def gauss_weight(self, g: builtins.int) -> builtins.float:
        r"""
        Weight of the `g`-th Gauss point.
        """
    def n_at_g(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        `N_i(ξ_g)` at the `g`-th Gauss point (length `nodes_per_cell`).
        """
    def dn_at_g(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        `∂N_i/∂ξ_j(ξ_g)` at the `g`-th Gauss point.
        
        Flat row-major: index `[i * ref_dim + j]`.
        """
    def jacobian(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Jacobian `J = ∂x/∂ξ` at the `g`-th Gauss point.
        """
    def det_jacobian(self, g: builtins.int) -> builtins.float:
        r"""
        `|J|` at the `g`-th Gauss point.
        """
    def dn_dx(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Physical derivatives `∂N_i/∂x_a` at the `g`-th Gauss point.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class ElementField:
    r"""
    Python wrapper for [`ElementField`].
    
    Owns the `ElementField` struct directly — no longer stored in the
    global store. Identity is the Python object identity.
    """
    def __new__(cls, fespace: FiniteElementSpace, components: typing.Sequence[builtins.str]) -> ElementField:
        r"""
        `ElementField(fespace, components)` — one sub-field per subspace
        of `fespace`, sharing the same `components` list. Zero-initialized.
        """
    @classmethod
    def with_components_per_subspace(cls, fespace: FiniteElementSpace, components_per_subspace: typing.Sequence[typing.Sequence[builtins.str]]) -> ElementField:
        r"""
        Explicit `components` list per subspace.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int) -> SubElementField: ...
    def subfield_count(self) -> builtins.int: ...
    def subfield(self, i: builtins.int) -> SubElementField: ...
    def unit(self) -> SubElementField:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubElementField) -> None: ...
    def add_subfield(self, sub: SubElementField) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def __add__(self, other: ElementField) -> ElementField:
        r"""
        `a + b` — merge two aggregates of this type into a fresh
        one (union of sub-objects, first-seen order). Sub-handles
        are **shared** (refcount bump), not deep-copied.
        """

@typing.final
class FiniteElementSpace:
    r"""
    Python wrapper for [`FiniteElementSpace`].
    
    Owns the `FiniteElementSpace` struct directly — no longer stored
    in the global store. Identity is the Python object identity.
    """
    def __new__(cls, mesh: Mesh, interpolation: builtins.str = 'LAGRANGE1', quadrature: builtins.str = 'GAUSS') -> FiniteElementSpace:
        r"""
        `FiniteElementSpace(mesh)` — Lagrange-1 + default Gauss for
        every submesh.
        
        `FiniteElementSpace(mesh, interpolation="LAGRANGE1", quadrature="GAUSS")`
        — same `(interpolation, quadrature)` applied to every submesh.
        """
    @classmethod
    def with_choices(cls, mesh: Mesh, choices: typing.Sequence[tuple[builtins.str, builtins.str]]) -> FiniteElementSpace:
        r"""
        Explicit `(interpolation, quadrature)` per submesh.
        """
    @classmethod
    def lagrange1(cls, mesh: Mesh) -> FiniteElementSpace:
        r"""
        Convenience: same as `FiniteElementSpace(mesh)`.
        """
    def element(self, sub_idx: builtins.int, cell_idx: builtins.int) -> Element:
        r"""
        `fes.element(sub_idx, cell_idx)` — Element view on a single cell.
        Mirrors `Mesh.cell(sub_idx, cell_idx)`.
        """
    def elements(self, sub_idx: builtins.int) -> builtins.list[Element]:
        r"""
        `fes.elements(sub_idx)` — list of every Element in subspace `sub_idx`.
        Mirrors `Mesh.cells(sub_idx)`.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int) -> SubFiniteElementSpace: ...
    def subspace_count(self) -> builtins.int: ...
    def subspace(self, i: builtins.int) -> SubFiniteElementSpace: ...
    def unit(self) -> SubFiniteElementSpace:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubFiniteElementSpace) -> None: ...
    def add_subspace(self, sub: SubFiniteElementSpace) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def __add__(self, other: FiniteElementSpace) -> FiniteElementSpace:
        r"""
        `a + b` — merge two aggregates of this type into a fresh
        one (union of sub-objects, first-seen order). Sub-handles
        are **shared** (refcount bump), not deep-copied.
        """

@typing.final
class Matrix:
    r"""
    Python wrapper for the aggregate [`Matrix`].
    
    Owns the `Matrix` struct directly — no longer stored in the global
    store. Identity is the Python object identity itself.
    """
    @property
    def symmetric(self) -> builtins.bool: ...
    def __new__(cls) -> Matrix:
        r"""
        `Matrix()` — empty aggregate. Populate via `add_sub_matrix`, or
        build blocks with `Matrix.block(...)` and compose them with `+`.
        """
    @classmethod
    def block(cls, row_support: typing.Any, col_support: typing.Any, dual_vars: typing.Sequence[builtins.str], primal_vars: typing.Sequence[builtins.str], ordering: builtins.str = 'nodes_then_vars', symmetric: builtins.bool = False) -> Matrix:
        r"""
        `Matrix.block(row_support, col_support, dual_vars, primal_vars, ordering="nodes_then_vars", symmetric=False)`
        — a single-block `Matrix` (unit aggregate). `row_support` /
        `col_support` may each be a `SubMesh` view or a **unitary** `Mesh`.
        `ordering` is `"nodes_then_vars"` (default) or `"vars_then_nodes"`.
        Fill entries via the block view (`block[0].add_entry(...)`) and
        compose several blocks with `+`, then `finalize()`.
        """
    def finalize(self) -> None:
        r"""
        Build the global DOF table and CSR. Must be called before any
        solver-facing method (`dense`, `mul_dense`, …).
        """
    def n_rows(self) -> builtins.int: ...
    def n_cols(self) -> builtins.int: ...
    def entry_count(self) -> builtins.int: ...
    def field_names(self) -> builtins.list[builtins.str]: ...
    def row_dofs(self) -> builtins.list[tuple[builtins.int, builtins.str]]: ...
    def col_dofs(self) -> builtins.list[tuple[builtins.int, builtins.str]]: ...
    def get(self, row_node: Node, row_field: builtins.str, col_node: Node, col_field: builtins.str) -> builtins.float: ...
    def dense(self) -> builtins.list[builtins.float]: ...
    def mul_dense(self, x: typing.Sequence[builtins.float]) -> builtins.list[builtins.float]: ...
    def entries(self) -> builtins.list[tuple[builtins.int, builtins.str, builtins.int, builtins.str, builtins.float]]:
        r"""
        List of `(row_node, row_field, col_node, col_field, value)`
        tuples — every entry across every block, in block-insertion order.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int) -> SubMatrix: ...
    def sub_matrix_count(self) -> builtins.int: ...
    def sub_matrix(self, i: builtins.int) -> SubMatrix: ...
    def unit(self) -> SubMatrix:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubMatrix) -> None: ...
    def add_sub_matrix(self, sub: SubMatrix) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def __add__(self, other: Matrix) -> Matrix:
        r"""
        `a + b` — merge two aggregates of this type into a fresh
        one (union of sub-objects, first-seen order). Sub-handles
        are **shared** (refcount bump), not deep-copied.
        """

@typing.final
class Mesh:
    r"""
    Python wrapper for [`Mesh`].
    
    Owns the `Mesh` struct directly — `Mesh` is no longer kept in the
    global store. Identity is the Python object identity itself
    (two Python references to the same `PyMesh` see the same submeshes).
    """
    def __new__(cls, config: Configuration, element_type: typing.Optional[builtins.str] = None) -> Mesh:
        r"""
        `Mesh(config)` — empty mesh.
        `Mesh(config, element_type)` — mesh with one pre-created submesh.
        """
    def element_types(self) -> builtins.list[builtins.str]: ...
    def cell_counts(self) -> builtins.list[builtins.int]: ...
    def node(self, submesh_idx: builtins.int, cell_idx: builtins.int, node_idx: builtins.int) -> Node: ...
    def cell(self, submesh_idx: builtins.int, cell_idx: builtins.int) -> Cell:
        r"""
        `mesh.cell(submesh_idx, cell_idx)` → `Cell` view; same thing
        as `mesh[submesh_idx][cell_idx]`.
        """
    def cell_count(self) -> builtins.int: ...
    def plot(self, view: typing.Optional[tuple[builtins.float, builtins.float, builtins.float]] = None, save: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, show_axes: builtins.bool = True, field: typing.Optional[NodeField] = None, component: typing.Optional[builtins.str] = None, vmin: typing.Optional[builtins.float] = None, vmax: typing.Optional[builtins.float] = None) -> None:
        r"""
        Visualize this mesh (every submesh in its own colour, or
        coloured by a `NodeField` if `field` is supplied). See
        `SubMesh.plot` for the meaning of `view`, `save`, `show_axes`,
        `field` and `component`.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int) -> SubMesh: ...
    def submesh_count(self) -> builtins.int: ...
    def submesh(self, i: builtins.int) -> SubMesh: ...
    def unit(self) -> SubMesh:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubMesh) -> None: ...
    def add_submesh(self, sub: SubMesh) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def __add__(self, other: Mesh) -> Mesh:
        r"""
        `a + b` — merge two aggregates of this type into a fresh
        one (union of sub-objects, first-seen order). Sub-handles
        are **shared** (refcount bump), not deep-copied.
        """

@typing.final
class Model:
    r"""
    Python wrapper for [`Model`].
    
    Owns the `Model` struct directly — no longer stored in the global
    store. Identity is the Python object identity itself.
    """
    def __new__(cls) -> Model: ...
    @classmethod
    def heat_conduction(cls, fespace: FiniteElementSpace) -> Model:
        r"""
        `Model.heat_conduction(fespace)` — heat-conduction model spanning
        **every** subspace of `fespace` (one zone per subspace). A
        single-subspace space gives the unit case; several give one zone
        each. Compose heterogeneous physics with `+`:
        `Model.heat_conduction(fes) + Model.dirichlet(...)`.
        """
    @classmethod
    def dirichlet(cls, primal_var: builtins.str, primal_dual: builtins.str, constrained_nodes: typing.Sequence[Node]) -> Model:
        r"""
        `Model.dirichlet(primal_var, primal_dual, constrained_nodes)` —
        Dirichlet-constraint model (a single sub-model) imposed via
        Lagrange multipliers. `constrained_nodes` is a list of `Node`
        objects. `primal_var` is the constrained primary variable (e.g.
        `"T"`); `primal_dual` is the dual variable of the primary physics
        it targets (e.g. `"q"` for heat conduction) — see the model
        chapter of the book for the full semantics.
        """
    def primal_vars(self) -> builtins.list[builtins.str]: ...
    def dual_vars(self) -> builtins.list[builtins.str]: ...
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int) -> SubModel: ...
    def sub_model_count(self) -> builtins.int: ...
    def sub_model(self, i: builtins.int) -> SubModel: ...
    def unit(self) -> SubModel:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubModel) -> None: ...
    def add_sub_model(self, sub: SubModel) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def __add__(self, other: Model) -> Model:
        r"""
        `a + b` — merge two aggregates of this type into a fresh
        one (union of sub-objects, first-seen order). Sub-handles
        are **shared** (refcount bump), not deep-copied.
        """

@typing.final
class Node:
    r"""
    Python wrapper for [`Node`].
    """
    @property
    def id(self) -> builtins.int: ...
    def coord(self) -> builtins.list[builtins.float]: ...
    def set_coord(self, coords: typing.Sequence[builtins.float]) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class NodeField:
    r"""
    Python wrapper for [`NodeField`].
    """
    def __new__(cls, support: typing.Any, components: typing.Sequence[builtins.str]) -> NodeField:
        r"""
        `NodeField(support, components)` — zero-initialized field over the
        POI1 nodes of `support`. `support` may be a `SubMesh` or a
        **unitary** `Mesh` (the parent→sub coercion: a one-submesh mesh is
        accepted directly, so callers rarely need `mesh[0]`).
        """
    def node_count(self) -> builtins.int: ...
    def component_count(self) -> builtins.int: ...
    def components(self) -> builtins.list[builtins.str]: ...
    def get(self, node_idx: builtins.int, comp_idx: builtins.int) -> builtins.float: ...
    def set(self, node_idx: builtins.int, comp_idx: builtins.int, value: builtins.float) -> None: ...
    def get_by_node(self, node: Node, comp_idx: builtins.int) -> builtins.float: ...
    def set_by_node(self, node: Node, comp_idx: builtins.int, value: builtins.float) -> None: ...
    def component_index(self, name: builtins.str) -> typing.Optional[builtins.int]: ...
    def node_values(self, node_idx: builtins.int) -> builtins.list[builtins.float]: ...
    def support_submesh(self) -> SubMesh: ...
    def support_mesh(self) -> Mesh: ...
    def value(self, node: Node, component: builtins.str) -> builtins.float: ...
    def set_value(self, node: Node, component: builtins.str, value: builtins.float) -> None: ...
    def add_to_component(self, component: builtins.str, scalar: builtins.float) -> None: ...
    def sub_to_component(self, component: builtins.str, scalar: builtins.float) -> None: ...
    def mul_to_component(self, component: builtins.str, scalar: builtins.float) -> None: ...
    def div_to_component(self, component: builtins.str, scalar: builtins.float) -> None: ...
    def __add__(self, rhs: typing.Any) -> NodeField:
        r"""
        `field + x` — `x` may be a scalar (added to every value) or another
        `NodeField` (component-wise addition over the union of supports).
        """
    def __sub__(self, rhs: builtins.float) -> NodeField: ...
    def __mul__(self, rhs: builtins.float) -> NodeField: ...
    def __truediv__(self, rhs: builtins.float) -> NodeField: ...
    def __getitem__(self, key: tuple[Node, builtins.str]) -> builtins.float:
        r"""
        `field[node, "UX"]` — raises IndexError if absent.
        """
    def __setitem__(self, key: tuple[Node, builtins.str], value: builtins.float) -> None:
        r"""
        `field[node, "UX"] = v` — raises IndexError if absent.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class SubElementField:
    r"""
    Python wrapper for [`SubElementField`].
    """
    def cell_count(self) -> builtins.int: ...
    def gauss_count(self) -> builtins.int: ...
    def component_count(self) -> builtins.int: ...
    def components(self) -> builtins.list[builtins.str]: ...
    def component_index(self, name: builtins.str) -> typing.Optional[builtins.int]: ...
    def get(self, cell: builtins.int, gauss: builtins.int, comp: builtins.int) -> builtins.float: ...
    def set(self, cell: builtins.int, gauss: builtins.int, comp: builtins.int, value: builtins.float) -> None: ...
    def value(self, cell: builtins.int, gauss: builtins.int, component: builtins.str) -> builtins.float: ...
    def set_value(self, cell: builtins.int, gauss: builtins.int, component: builtins.str, value: builtins.float) -> None: ...
    def point_values(self, cell: builtins.int, gauss: builtins.int) -> builtins.list[builtins.float]: ...
    def set_uniform(self, component: builtins.str, value: builtins.float) -> None: ...
    def set_cell_uniform(self, cell: builtins.int, component: builtins.str, value: builtins.float) -> None: ...
    def add_to_component(self, component: builtins.str, scalar: builtins.float) -> None: ...
    def sub_to_component(self, component: builtins.str, scalar: builtins.float) -> None: ...
    def mul_to_component(self, component: builtins.str, scalar: builtins.float) -> None: ...
    def div_to_component(self, component: builtins.str, scalar: builtins.float) -> None: ...
    def __add__(self, rhs: builtins.float) -> SubElementField: ...
    def __sub__(self, rhs: builtins.float) -> SubElementField: ...
    def __mul__(self, rhs: builtins.float) -> SubElementField: ...
    def __truediv__(self, rhs: builtins.float) -> SubElementField: ...
    def __getitem__(self, key: tuple[builtins.int, builtins.int, builtins.str]) -> builtins.float:
        r"""
        `field[cell, gauss, "name"]` — raises ValueError if the component
        is unknown.
        """
    def __setitem__(self, key: tuple[builtins.int, builtins.int, builtins.str], value: builtins.float) -> None:
        r"""
        `field[cell, gauss, "name"] = value`.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class SubFiniteElementSpace:
    r"""
    Python wrapper for [`SubFiniteElementSpace`].
    """
    @property
    def element_type(self) -> builtins.str: ...
    @property
    def interpolation(self) -> builtins.str: ...
    @property
    def quadrature(self) -> builtins.str: ...
    @property
    def ref_dim(self) -> builtins.int: ...
    @property
    def space_dim(self) -> builtins.int: ...
    @property
    def nodes_per_cell(self) -> builtins.int: ...
    def cell_count(self) -> builtins.int: ...
    def gauss_count(self) -> builtins.int: ...
    def gauss_xi(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Reference coordinates of the `g`-th Gauss point.
        """
    def gauss_weight(self, g: builtins.int) -> builtins.float:
        r"""
        Weight of the `g`-th Gauss point.
        """
    def n_at_g(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        `N_i(ξ_g)` at the `g`-th Gauss point (flat, length `nodes_per_cell`).
        """
    def dn_at_g(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        `∂N_i/∂ξ_j(ξ_g)` at the `g`-th Gauss point.
        
        Flat row-major: index `[i * ref_dim + j]`.
        """
    def jacobian(self, cell_idx: builtins.int, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Jacobian `J = ∂x/∂ξ` of cell `cell_idx` at Gauss point `g`.
        
        Flat row-major buffer of length `space_dim × ref_dim`,
        indexed `[a * ref_dim + k]`.
        """
    def det_jacobian(self, cell_idx: builtins.int, g: builtins.int) -> builtins.float:
        r"""
        `|J|` — `|det(J)|` if `space_dim == ref_dim`, else
        `sqrt(det(JᵀJ))`. Always non-negative.
        """
    def dn_dx(self, cell_idx: builtins.int, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Physical derivatives `∂N_i/∂x_a` of cell `cell_idx` at Gauss
        point `g`. Flat row-major buffer of length
        `nodes_per_cell × space_dim`, indexed `[i * space_dim + a]`.
        """
    def element(self, i: builtins.int) -> Element:
        r"""
        Element view on the `i`-th cell of this subspace.
        """
    def elements(self) -> builtins.list[Element]:
        r"""
        All elements as a Python list.
        """
    def __len__(self) -> builtins.int:
        r"""
        `len(subspace)` → number of elements (= number of cells).
        """
    def __getitem__(self, idx: builtins.int) -> Element:
        r"""
        `subspace[i]` → `Element` view on element `i`. Supports negative
        indices and raises `IndexError` out of range so
        `for el in subspace:` works.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class SubMatrix:
    r"""
    Python wrapper for [`SubMatrix`] — one COO block of the global matrix.
    """
    @property
    def symmetric(self) -> builtins.bool: ...
    def add_entry(self, row_node: Node, row_field: builtins.str, col_node: Node, col_field: builtins.str, value: builtins.float) -> None: ...
    def get(self, row_node: Node, row_field: builtins.str, col_node: Node, col_field: builtins.str) -> builtins.float: ...
    def n_rows(self) -> builtins.int: ...
    def n_cols(self) -> builtins.int: ...
    def entry_count(self) -> builtins.int: ...
    def field_names(self) -> builtins.list[builtins.str]: ...
    def row_dofs(self) -> builtins.list[tuple[builtins.int, builtins.str]]:
        r"""
        `(node_id, field_name)` tuples for each row, in order.
        """
    def col_dofs(self) -> builtins.list[tuple[builtins.int, builtins.str]]:
        r"""
        `(node_id, field_name)` tuples for each column, in order.
        """
    def dense(self) -> builtins.list[builtins.float]:
        r"""
        Dense row-major buffer, length `n_rows × n_cols`.
        """
    def mul_dense(self, x: typing.Sequence[builtins.float]) -> builtins.list[builtins.float]:
        r"""
        `y = A · x` (dense).
        """
    def entries(self) -> builtins.list[tuple[builtins.int, builtins.str, builtins.int, builtins.str, builtins.float]]:
        r"""
        List of `(row_node, row_field, col_node, col_field, value)`
        tuples, in insertion order.
        """
    def __len__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class SubMesh:
    r"""
    Python wrapper for [`SubMesh`].
    """
    @property
    def element_type(self) -> builtins.str: ...
    @property
    def face_color(self) -> tuple[builtins.int, builtins.int, builtins.int]:
        r"""
        Face colour as an `(r, g, b)` tuple of bytes.
        """
    @face_color.setter
    def face_color(self, value: tuple[builtins.int, builtins.int, builtins.int]) -> None:
        r"""
        Set the face colour from an `(r, g, b)` tuple of bytes.
        """
    def add_cell(self, nodes: typing.Sequence[Node]) -> builtins.int: ...
    def cell_count(self) -> builtins.int: ...
    def plot(self, view: typing.Optional[tuple[builtins.float, builtins.float, builtins.float]] = None, save: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, show_axes: builtins.bool = True, field: typing.Optional[NodeField] = None, component: typing.Optional[builtins.str] = None, vmin: typing.Optional[builtins.float] = None, vmax: typing.Optional[builtins.float] = None) -> None:
        r"""
        Visualize this submesh.
        
        - `save=None`: interactive window (requires `viz-interactive`).
        - `save="<path>.png"` or `.svg`: image file.
        - `view`: optional `(yaw, pitch, scale)` triple; default is iso.
        - `show_axes`: draw the X/Y/Z orientation gizmo in the bottom-left
          corner (default `True`). In the interactive window, the key
          `A` toggles it at runtime.
        - `field`: optional `NodeField` whose values colour each cell
          (per-cell value = mean over the cell's nodes of the chosen
          component). Default `None` ⇒ uniform face colour.
        - `component`: component name to display when `field` is set
          (defaults to the field's first component). In the
          interactive window, click the top button or press `Tab` to
          cycle through every component.
        - `vmin` / `vmax`: pin the bottom / top of the colour scale (and
          of the colorbar drawn on the right). Either may be left `None`
          to track the data's own min / max for that bound.
        """
    def __len__(self) -> builtins.int:
        r"""
        `len(submesh)` → number of cells.
        """
    def __getitem__(self, idx: builtins.int) -> Cell:
        r"""
        `submesh[i]` → `Cell` view on cell i. Supports negative
        indices and raises `IndexError` out of range so
        `for cell in submesh:` works.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class SubModel:
    r"""
    Python wrapper for [`SubModel`].
    """
    def primal_vars(self) -> builtins.list[builtins.str]: ...
    def dual_vars(self) -> builtins.list[builtins.str]: ...
    def multiplier_mesh(self) -> Mesh:
        r"""
        POI1 `Mesh` of the multiplier nodes (Lagrange physics only — empty
        otherwise). Build a load `NodeField` on `mesh[0]` to impose the
        constrained values, or read the nodes via `mesh.node(0, i, 0)`.
        """
    def material_components(self) -> typing.Optional[builtins.list[builtins.str]]:
        r"""
        Names of the material components this sub-model expects, or
        `None` for physics that don't need material data (Dirichlet, …).
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...

def circle_seg2(center: Node, normal: typing.Sequence[builtins.float], radius: builtins.float, n_elems: builtins.int) -> Mesh: ...

def consolidate(mesh: Mesh) -> Mesh:
    r"""
    Fuse submeshes of the same element type into one and drop duplicate
    cells. Returns a new mesh with one submesh per element type, in
    first-seen order.
    """

def coordinates(mesh: Mesh, components: typing.Optional[typing.Sequence[builtins.str]] = None) -> NodeField:
    r"""
    Build a `NodeField` carrying the coordinates of every node of `mesh`.
    
    One component per requested axis (`"X"`, `"Y"`, `"Z"`). `components=None`
    requests all the axes the mesh's `Configuration` has (`["X"]` in 1-D,
    `["X", "Y"]` in 2-D, `["X", "Y", "Z"]` in 3-D). A non-POI1 mesh is
    converted to POI1 internally (see `to_poi1`); the support is the unique
    nodes of the mesh, in order of first appearance.
    """

def extrude(mesh: Mesh, direction: typing.Sequence[builtins.float], n_layers: builtins.int) -> Mesh: ...

def fill_surface(contour: Mesh, element_type: builtins.str, max_edge_length: typing.Optional[builtins.float] = None, min_angle_deg: typing.Optional[builtins.float] = None) -> Mesh: ...

def from_live_nodes(config: Configuration) -> Mesh: ...

def line_seg2(a: Node, b: Node, n_elems: builtins.int) -> Mesh: ...

def mass(model: Model) -> Matrix:
    r"""
    Assemble the mass matrix `M` of `model`.
    
    v0 stub: no physics has a mass term yet, so this returns an empty
    finalized `Matrix` with the model's DOF layout.
    """

def material_field(model: Model, components_and_values: typing.Sequence[tuple[builtins.str, builtins.float]]) -> ElementField:
    r"""
    Build a material `ElementField` applying the same uniform
    `(component, value)` pairs to every material-hungry sub-model of
    `model`. Sub-models that need no material (Dirichlet, …) are skipped.
    """

def material_field_per_sub_model(model: Model, components_and_values_per_sub_model: typing.Sequence[typing.Sequence[tuple[builtins.str, builtins.float]]]) -> ElementField:
    r"""
    Build a material `ElementField` where each sub-model gets its own
    `(component, value)` list. The outer list length must equal
    `model.sub_model_count()`. An empty inner list **skips** the matching
    sub-model (typical for Dirichlet).
    """

def merge(a: NodeField, b: NodeField) -> NodeField:
    r"""
    Merge two node fields over the union of their supports.
    
    Keeps each field's value where only one is defined, `0.0` where
    neither is. Errors if the two fields hold different values at the same
    `(node, component)` pair, or are attached to different `Configuration`s.
    """

def restrict(field: NodeField, mesh: Mesh) -> NodeField:
    r"""
    Restrict `field` to the nodes used by `mesh`.
    
    Returns a new `NodeField` with the same components, supported on the
    unique nodes of `mesh` (order of first appearance). Nodes of `mesh`
    absent from `field` are assigned `0.0`. Errors if `mesh` and `field`
    are attached to different `Configuration`s.
    """

def set_swap_dir(path: builtins.str | os.PathLike | pathlib.Path) -> None:
    r"""
    Set the swap directory (Python binding of [`store::set_swap_dir`]).
    """

def solve(matrix: Matrix, rhs: NodeField) -> NodeField:
    r"""
    `pyrucast.solve(matrix, rhs) -> NodeField`
    
    Dense LU solver. See [`crate::ops::solver::lu::solve`] for the semantics
    of the rhs and of the returned NodeField.
    """

def stiffness(model: Model, materials: ElementField) -> Matrix:
    r"""
    Assemble the stiffness matrix `K` of `model`.
    
    `materials` carries the per-zone material data: every sub-model that
    needs it picks the `SubElementField` whose FE subspace matches its own.
    """

def sub_material_field(sub_model: SubModel, components_and_values: typing.Sequence[tuple[builtins.str, builtins.float]]) -> SubElementField:
    r"""
    Build the material `SubElementField` of one sub-model.
    
    `sub_material_field(sub_model, [("k", 1.0), ...])` — fresh
    SubElementField on the sub-model's FE subspace, pre-filled with the
    given uniform value per declared component. Errors for physics that
    need no material (e.g. Dirichlet).
    """

def swap_dir() -> pathlib.Path:
    r"""
    Return the effective swap directory (Python binding of [`store::swap_dir`]).
    """

def sweep_qua4(mesh_a: Mesh, mesh_b: Mesh, n_layers: builtins.int) -> Mesh: ...

def to_poi1(mesh: Mesh) -> Mesh:
    r"""
    Convert a mesh to POI1, submesh by submesh.
    
    Returns a new mesh with the same number of submeshes; each output
    submesh is a POI1 submesh holding the de-duplicated nodes of the
    corresponding input submesh, in order of first appearance.
    """

