# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing
__all__ = [
    "Cell",
    "Configuration",
    "Element",
    "ElementField",
    "FiniteElementSpace",
    "Matrix",
    "Mesh",
    "Model",
    "Node",
    "NodeField",
    "SubElementField",
    "SubFiniteElementSpace",
    "SubMatrix",
    "SubMesh",
    "SubModel",
    "circle_seg2",
    "consolidate",
    "coordinates",
    "extrude",
    "fill_surface",
    "from_live_nodes",
    "line_seg2",
    "mass",
    "material_field",
    "material_field_per_sub_model",
    "merge",
    "restrict",
    "set_swap_dir",
    "solve",
    "stiffness",
    "sub_material_field",
    "swap_dir",
    "sweep_qua4",
    "to_poi1",
]

@typing.final
class Cell:
    r"""
    One cell of a mesh — the ordered nodes of a single element.
    
    A read-only view obtained by indexing a submesh (`submesh[i]`) or via
    `mesh.cell(submesh, cell)`. `len(cell)` is its node count; iterating a
    cell yields its `Node`s.
    """
    @property
    def index(self) -> builtins.int:
        r"""
        Index of this cell within its submesh.
        """
    @property
    def element_type(self) -> builtins.str:
        r"""
        Element type name of this cell (e.g. `"TRI3"`).
        """
    def nodes(self) -> builtins.list[Node]:
        r"""
        Materialised nodes (each one refcounted on the
        Configuration).
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int) -> Node:
        r"""
        `cell[j]` — j-th node of the cell. Supports negative indices
        and raises `IndexError` out of range so `for node in cell:` works.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> builtins.str:
        r"""
        Full content (third display level): values / topology, beyond
        `repr`'s bounded structure.
        """

@typing.final
class Configuration:
    r"""
    The registry of live nodes and their coordinates, in a fixed spatial
    dimension.
    
    Create one with `Configuration(dim)`, then add nodes with
    `add_node([x, y, ...])`. Every mesh, node and field is attached to a
    `Configuration`.
    """
    @property
    def dim(self) -> builtins.int:
        r"""
        Spatial dimension of the coordinates (1, 2 or 3).
        """
    @property
    def active_set(self) -> builtins.int:
        r"""
        Index of the active coordinate set.
        """
    def __new__(cls, dim: builtins.int) -> Configuration:
        r"""
        `Configuration(dim)` — an empty configuration in `dim` dimensions.
        """
    def node_count(self) -> builtins.int:
        r"""
        Number of live nodes.
        """
    def capacity(self) -> builtins.int:
        r"""
        Number of allocated node slots (live plus not-yet-collected).
        """
    def is_alive(self, id: builtins.int) -> builtins.bool:
        r"""
        Whether node `id` is still live (not garbage-collected).
        """
    def add_node(self, coords: typing.Sequence[builtins.float]) -> Node:
        r"""
        Add a node at `coords` and return it as a `Node` (refcount = 1).
        """
    def acquire(self, id: builtins.int) -> Node:
        r"""
        Return an additional `Node` for an existing id (refcount += 1).
        """
    def refcount(self, id: builtins.int) -> builtins.int:
        r"""
        Reference count of node `id` (how many holders keep it alive).
        """
    def gc(self) -> builtins.int:
        r"""
        Run the garbage collector; return the number of collected nodes.
        """
    def coord(self, id: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Coordinates of node `id` in the active coordinate set.
        """
    def set_coord(self, id: builtins.int, coords: typing.Sequence[builtins.float]) -> None:
        r"""
        Overwrite the coordinates of node `id` in the active set.
        """
    def add_coord_set(self, name: builtins.str) -> builtins.int:
        r"""
        Add a named alternative coordinate set (same nodes, new coordinates);
        returns its index.
        """
    def switch_to(self, set: builtins.int) -> None:
        r"""
        Make coordinate set `set` the active one.
        """
    def set_names(self) -> builtins.list[builtins.str]:
        r"""
        Names of the coordinate sets, by index.
        """
    def permutation(self) -> typing.Optional[builtins.list[builtins.int]]:
        r"""
        Current node permutation (a renumbering), or `None` if unset.
        """
    def set_permutation(self, perm: typing.Sequence[builtins.int]) -> None:
        r"""
        Set a node permutation (a renumbering of the nodes).
        """
    def clear_permutation(self) -> None:
        r"""
        Drop any node permutation.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> builtins.str:
        r"""
        Full content (third display level): values / topology, beyond
        `repr`'s bounded structure.
        """

@typing.final
class Element:
    r"""
    A single finite element — its geometry together with the interpolation
    and quadrature of its space.
    
    A read-only view obtained by indexing a finite-element subspace
    (`fes[i][j]`); not constructed directly.
    """
    @property
    def index(self) -> builtins.int:
        r"""
        Index of this element within its subspace.
        """
    @property
    def nodes_per_cell(self) -> builtins.int:
        r"""
        Number of nodes of this element.
        """
    @property
    def space_dim(self) -> builtins.int:
        r"""
        Spatial dimension the element lives in.
        """
    @property
    def ref_dim(self) -> builtins.int:
        r"""
        Reference (parametric) dimension of the element.
        """
    @property
    def gauss_count(self) -> builtins.int:
        r"""
        Number of Gauss (quadrature) points.
        """
    def cell(self) -> Cell:
        r"""
        Underlying mesh cell view.
        """
    def nodes(self) -> builtins.list[Node]:
        r"""
        Materialised nodes of this element (each refcounted on the
        Configuration) — symmetric with `Cell.nodes()`.
        """
    def gauss_xi(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Reference coordinates of the `g`-th Gauss point.
        """
    def gauss_weight(self, g: builtins.int) -> builtins.float:
        r"""
        Weight of the `g`-th Gauss point.
        """
    def n_at_g(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        `N_i(ξ_g)` at the `g`-th Gauss point (length `nodes_per_cell`).
        """
    def dn_at_g(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        `∂N_i/∂ξ_j(ξ_g)` at the `g`-th Gauss point.
        
        Flat row-major: index `[i * ref_dim + j]`.
        """
    def jacobian(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Jacobian `J = ∂x/∂ξ` at the `g`-th Gauss point.
        """
    def det_jacobian(self, g: builtins.int) -> builtins.float:
        r"""
        `|J|` at the `g`-th Gauss point.
        """
    def dn_dx(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Physical derivatives `∂N_i/∂x_a` at the `g`-th Gauss point.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> builtins.str:
        r"""
        Full content (third display level): values / topology, beyond
        `repr`'s bounded structure.
        """

@typing.final
class ElementField:
    r"""
    A field of per-element values (e.g. material properties), one block per
    finite-element zone.
    
    Build with `ElementField(fes, components)` or `material_field(model, ...)`;
    index it (`field[i]`) to reach a `SubElementField`, compose zones
    with `+`.
    """
    def __new__(cls, fespace: FiniteElementSpace, components: typing.Sequence[builtins.str]) -> ElementField:
        r"""
        `ElementField(fespace, components)` — one sub-field per subspace
        of `fespace`, sharing the same `components` list. Zero-initialized.
        """
    @classmethod
    def with_components_per_subspace(cls, fespace: FiniteElementSpace, components_per_subspace: typing.Sequence[typing.Sequence[builtins.str]]) -> ElementField:
        r"""
        Explicit `components` list per subspace.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int) -> SubElementField: ...
    def subfield_count(self) -> builtins.int: ...
    def subfield(self, i: builtins.int) -> SubElementField: ...
    def unit(self) -> SubElementField:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubElementField) -> None: ...
    def add_subfield(self, sub: SubElementField) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> builtins.str:
        r"""
        Full content (third display level): every sub-object's
        values/topology, beyond `repr`'s bounded structure.
        """
    def __add__(self, other: ElementField) -> ElementField:
        r"""
        `a + b` — merge two aggregates of this type into a fresh
        one (union of sub-objects, first-seen order). Sub-handles
        are **shared** (refcount bump), not deep-copied.
        """

@typing.final
class FiniteElementSpace:
    r"""
    The finite-element discretization of a mesh: one subspace per submesh,
    each carrying an interpolation and a quadrature rule.
    
    Build from a `Mesh` with `FiniteElementSpace(mesh)` (or
    `.with_choices(...)` per submesh); index it (`fes[i]`) to reach a
    `SubFiniteElementSpace`, compose several with `+`.
    """
    def __new__(cls, mesh: Mesh, interpolation: builtins.str = 'LAGRANGE1', quadrature: builtins.str = 'GAUSS') -> FiniteElementSpace:
        r"""
        `FiniteElementSpace(mesh)` — Lagrange-1 + default Gauss for
        every submesh.
        
        `FiniteElementSpace(mesh, interpolation="LAGRANGE1", quadrature="GAUSS")`
        — same `(interpolation, quadrature)` applied to every submesh.
        """
    @classmethod
    def with_choices(cls, mesh: Mesh, choices: typing.Sequence[tuple[builtins.str, builtins.str]]) -> FiniteElementSpace:
        r"""
        Explicit `(interpolation, quadrature)` per submesh.
        """
    @classmethod
    def lagrange1(cls, mesh: Mesh) -> FiniteElementSpace:
        r"""
        Convenience: same as `FiniteElementSpace(mesh)`.
        """
    def element(self, sub_idx: builtins.int, cell_idx: builtins.int) -> Element:
        r"""
        `fes.element(sub_idx, cell_idx)` — Element view on a single cell.
        Mirrors `Mesh.cell(sub_idx, cell_idx)`.
        """
    def elements(self, sub_idx: builtins.int) -> builtins.list[Element]:
        r"""
        `fes.elements(sub_idx)` — list of every Element in subspace `sub_idx`.
        Mirrors `Mesh.cells(sub_idx)`.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int) -> SubFiniteElementSpace: ...
    def subspace_count(self) -> builtins.int: ...
    def subspace(self, i: builtins.int) -> SubFiniteElementSpace: ...
    def unit(self) -> SubFiniteElementSpace:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubFiniteElementSpace) -> None: ...
    def add_subspace(self, sub: SubFiniteElementSpace) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> builtins.str:
        r"""
        Full content (third display level): every sub-object's
        values/topology, beyond `repr`'s bounded structure.
        """
    def __add__(self, other: FiniteElementSpace) -> FiniteElementSpace:
        r"""
        `a + b` — merge two aggregates of this type into a fresh
        one (union of sub-objects, first-seen order). Sub-handles
        are **shared** (refcount bump), not deep-copied.
        """

@typing.final
class Matrix:
    r"""
    A global finite-element matrix, assembled from rectangular blocks
    (`SubMatrix`).
    
    Build blocks with `Matrix.block(...)`, compose them with `+`, then call
    `finalize()` before solving. Index it (`matrix[i]`) to reach a block.
    """
    @property
    def symmetric(self) -> builtins.bool:
        r"""
        Whether the matrix is declared symmetric.
        """
    def __new__(cls) -> Matrix:
        r"""
        `Matrix()` — empty aggregate. Populate via `add_sub_matrix`, or
        build blocks with `Matrix.block(...)` and compose them with `+`.
        """
    @classmethod
    def block(cls, row_support: typing.Any, col_support: typing.Any, dual_vars: typing.Sequence[builtins.str], primal_vars: typing.Sequence[builtins.str], ordering: builtins.str = 'nodes_then_vars', symmetric: builtins.bool = False) -> Matrix:
        r"""
        `Matrix.block(row_support, col_support, dual_vars, primal_vars, ordering="nodes_then_vars", symmetric=False)`
        — a single-block `Matrix` (unit aggregate). `row_support` /
        `col_support` may each be a `SubMesh` view or a **unitary** `Mesh`.
        `ordering` is `"nodes_then_vars"` (default) or `"vars_then_nodes"`.
        Fill entries via the block view (`block[0].add_entry(...)`) and
        compose several blocks with `+`, then `finalize()`.
        """
    def finalize(self) -> None:
        r"""
        Build the global DOF table and CSR. Must be called before any
        solver-facing method (`dense`, `mul_dense`, …).
        """
    def n_rows(self) -> builtins.int:
        r"""
        Total number of rows of the (finalized) global matrix.
        """
    def n_cols(self) -> builtins.int:
        r"""
        Total number of columns of the (finalized) global matrix.
        """
    def entry_count(self) -> builtins.int:
        r"""
        Total number of stored entries across all blocks.
        """
    def field_names(self) -> builtins.list[builtins.str]:
        r"""
        Variable (field) names across the whole matrix.
        """
    def row_dofs(self) -> builtins.list[tuple[builtins.int, builtins.str]]:
        r"""
        `(node_id, field_name)` of each global row, in order.
        """
    def col_dofs(self) -> builtins.list[tuple[builtins.int, builtins.str]]:
        r"""
        `(node_id, field_name)` of each global column, in order.
        """
    def get(self, row_node: Node, row_field: builtins.str, col_node: Node, col_field: builtins.str) -> builtins.float:
        r"""
        Value at row `(row_node, row_field)`, column `(col_node, col_field)`.
        """
    def dense(self) -> builtins.list[builtins.float]:
        r"""
        Dense row-major buffer of the finalized matrix (`n_rows × n_cols`).
        """
    def mul_dense(self, x: typing.Sequence[builtins.float]) -> builtins.list[builtins.float]:
        r"""
        `y = A · x` against a dense vector `x`.
        """
    def entries(self) -> builtins.list[tuple[builtins.int, builtins.str, builtins.int, builtins.str, builtins.float]]:
        r"""
        List of `(row_node, row_field, col_node, col_field, value)`
        tuples — every entry across every block, in block-insertion order.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int) -> SubMatrix: ...
    def sub_matrix_count(self) -> builtins.int: ...
    def sub_matrix(self, i: builtins.int) -> SubMatrix: ...
    def unit(self) -> SubMatrix:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubMatrix) -> None: ...
    def add_sub_matrix(self, sub: SubMatrix) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> builtins.str:
        r"""
        Full content (third display level): every sub-object's
        values/topology, beyond `repr`'s bounded structure.
        """
    def __add__(self, other: Matrix) -> Matrix:
        r"""
        `a + b` — merge two aggregates of this type into a fresh
        one (union of sub-objects, first-seen order). Sub-handles
        are **shared** (refcount bump), not deep-copied.
        """

@typing.final
class Mesh:
    r"""
    A geometric mesh: a collection of submeshes, each holding the cells of a
    single element type.
    
    Build with `Mesh(config, element_type)` for one zone, compose several
    with `+`; index it (`mesh[i]`) to reach a `SubMesh`.
    """
    def __new__(cls, config: Configuration, element_type: typing.Optional[builtins.str] = None) -> Mesh:
        r"""
        `Mesh(config)` — empty mesh.
        `Mesh(config, element_type)` — mesh with one pre-created submesh.
        """
    def element_types(self) -> builtins.list[builtins.str]:
        r"""
        Element type name of each submesh, in order.
        """
    def cell_counts(self) -> builtins.list[builtins.int]:
        r"""
        Number of cells in each submesh, in order.
        """
    def node(self, submesh_idx: builtins.int, cell_idx: builtins.int, node_idx: builtins.int) -> Node:
        r"""
        The `node_idx`-th node of cell `cell_idx` in submesh `submesh_idx`.
        """
    def cell(self, submesh_idx: builtins.int, cell_idx: builtins.int) -> Cell:
        r"""
        `mesh.cell(submesh_idx, cell_idx)` → `Cell` view; same thing
        as `mesh[submesh_idx][cell_idx]`.
        """
    def cell_count(self) -> builtins.int:
        r"""
        Total number of cells across all submeshes.
        """
    def plot(self, view: typing.Optional[tuple[builtins.float, builtins.float, builtins.float]] = None, save: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, show_axes: builtins.bool = True, field: typing.Optional[NodeField] = None, component: typing.Optional[builtins.str] = None, vmin: typing.Optional[builtins.float] = None, vmax: typing.Optional[builtins.float] = None, cmap: typing.Optional[builtins.str] = None) -> None:
        r"""
        Visualize this mesh (every submesh in its own colour, or
        coloured by a `NodeField` if `field` is supplied). See
        `SubMesh.plot` for the meaning of `view`, `save`, `show_axes`,
        `field` and `component`.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int) -> SubMesh: ...
    def submesh_count(self) -> builtins.int: ...
    def submesh(self, i: builtins.int) -> SubMesh: ...
    def unit(self) -> SubMesh:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubMesh) -> None: ...
    def add_submesh(self, sub: SubMesh) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> builtins.str:
        r"""
        Full content (third display level): every sub-object's
        values/topology, beyond `repr`'s bounded structure.
        """
    def __add__(self, other: Mesh) -> Mesh:
        r"""
        `a + b` — merge two aggregates of this type into a fresh
        one (union of sub-objects, first-seen order). Sub-handles
        are **shared** (refcount bump), not deep-copied.
        """

@typing.final
class Model:
    r"""
    A physics problem: a collection of sub-models (heat conduction,
    Dirichlet BCs, ...) over finite-element spaces.
    
    Build sub-models with `Model.heat_conduction(fes)` / `Model.dirichlet(...)`
    and compose them with `+`; assemble with `stiffness` / `mass`.
    """
    def __new__(cls) -> Model:
        r"""
        `Model()` — an empty model; add physics with `+`.
        """
    @classmethod
    def heat_conduction(cls, fespace: FiniteElementSpace) -> Model:
        r"""
        `Model.heat_conduction(fespace)` — heat-conduction model spanning
        **every** subspace of `fespace` (one zone per subspace). A
        single-subspace space gives the unit case; several give one zone
        each. Compose heterogeneous physics with `+`:
        `Model.heat_conduction(fes) + Model.dirichlet(...)`.
        """
    @classmethod
    def dirichlet(cls, primal_var: builtins.str, primal_dual: builtins.str, constrained_nodes: typing.Sequence[Node]) -> Model:
        r"""
        `Model.dirichlet(primal_var, primal_dual, constrained_nodes)` —
        Dirichlet-constraint model (a single sub-model) imposed via
        Lagrange multipliers. `constrained_nodes` is a list of `Node`
        objects. `primal_var` is the constrained primary variable (e.g.
        `"T"`); `primal_dual` is the dual variable of the primary physics
        it targets (e.g. `"q"` for heat conduction) — see the model
        chapter of the book for the full semantics.
        """
    def primal_vars(self) -> builtins.list[builtins.str]:
        r"""
        Names of the primal (primary) variables across the whole model.
        """
    def dual_vars(self) -> builtins.list[builtins.str]:
        r"""
        Names of the dual variables across the whole model.
        """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, idx: builtins.int) -> SubModel: ...
    def sub_model_count(self) -> builtins.int: ...
    def sub_model(self, i: builtins.int) -> SubModel: ...
    def unit(self) -> SubModel:
        r"""
        The sole sub-object **view** of a unitary aggregate
        (exactly one sub), else a clear error. Use it where the
        single-zone case needs a sub method: `parent.unit().m(...)`.
        More honest than `parent[0]` (which silently takes the
        first of several) — see `CONVENTIONS.md`.
        """
    def add_sub(self, sub: SubModel) -> None: ...
    def add_sub_model(self, sub: SubModel) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> builtins.str:
        r"""
        Full content (third display level): every sub-object's
        values/topology, beyond `repr`'s bounded structure.
        """
    def __add__(self, other: Model) -> Model:
        r"""
        `a + b` — merge two aggregates of this type into a fresh
        one (union of sub-objects, first-seen order). Sub-handles
        are **shared** (refcount bump), not deep-copied.
        """

@typing.final
class Node:
    r"""
    A node of a `Configuration`: a stable identifier that carries the
    configuration it belongs to (and therefore its coordinates).
    
    Created via `Configuration.add_node([x, y, ...])`; passed wherever an
    API needs a node.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Stable integer id of this node within its `Configuration`.
        """
    def coord(self) -> builtins.list[builtins.float]:
        r"""
        This node's coordinates in the active coordinate set.
        """
    def set_coord(self, coords: typing.Sequence[builtins.float]) -> None:
        r"""
        Overwrite this node's coordinates.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> builtins.str:
        r"""
        Full content (third display level): values / topology, beyond
        `repr`'s bounded structure.
        """

@typing.final
class NodeField:
    r"""
    A field of values carried by mesh nodes — one scalar per
    `(node, component)`.
    
    Index it as `field[node, "X"]`. Build one with `coordinates(mesh)`, or
    derive it with `restrict` / `merge`; add fields or scalars with `+`.
    """
    def __new__(cls, support: typing.Any, components: typing.Sequence[builtins.str]) -> NodeField:
        r"""
        `NodeField(support, components)` — zero-initialized field over the
        POI1 nodes of `support`. `support` may be a `SubMesh` or a
        **unitary** `Mesh` (the parent→sub coercion: a one-submesh mesh is
        accepted directly, so callers rarely need `mesh[0]`).
        """
    def node_count(self) -> builtins.int:
        r"""
        Number of nodes in the support.
        """
    def component_count(self) -> builtins.int:
        r"""
        Number of components stored per node.
        """
    def components(self) -> builtins.list[builtins.str]:
        r"""
        Component names, in order.
        """
    def get(self, node_idx: builtins.int, comp_idx: builtins.int) -> builtins.float:
        r"""
        Value at node index `node_idx`, component index `comp_idx`.
        """
    def set(self, node_idx: builtins.int, comp_idx: builtins.int, value: builtins.float) -> None:
        r"""
        Set the value at node index `node_idx`, component index `comp_idx`.
        """
    def get_by_node(self, node: Node, comp_idx: builtins.int) -> builtins.float:
        r"""
        Value at `node`, component index `comp_idx`.
        """
    def set_by_node(self, node: Node, comp_idx: builtins.int, value: builtins.float) -> None:
        r"""
        Set the value at `node`, component index `comp_idx`.
        """
    def component_index(self, name: builtins.str) -> typing.Optional[builtins.int]:
        r"""
        Index of component `name`, or `None` if unknown.
        """
    def node_values(self, node_idx: builtins.int) -> builtins.list[builtins.float]:
        r"""
        All component values at node index `node_idx`, in order.
        """
    def support_submesh(self) -> SubMesh:
        r"""
        The POI1 `SubMesh` this field is supported on.
        """
    def support_mesh(self) -> Mesh:
        r"""
        The POI1 `Mesh` this field is supported on.
        """
    def value(self, node: Node, component: builtins.str) -> builtins.float:
        r"""
        Value at `node` for the named `component`.
        """
    def set_value(self, node: Node, component: builtins.str, value: builtins.float) -> None:
        r"""
        Set the value at `node` for the named `component`.
        """
    def add_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Add `scalar` to every value of `component` (in place).
        """
    def sub_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Subtract `scalar` from every value of `component` (in place).
        """
    def mul_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Multiply every value of `component` by `scalar` (in place).
        """
    def div_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Divide every value of `component` by `scalar` (in place).
        """
    def __add__(self, rhs: typing.Any) -> NodeField:
        r"""
        `field + x` — `x` may be a scalar (added to every value) or another
        `NodeField` (component-wise addition over the union of supports).
        """
    def __sub__(self, rhs: builtins.float) -> NodeField: ...
    def __mul__(self, rhs: builtins.float) -> NodeField: ...
    def __truediv__(self, rhs: builtins.float) -> NodeField: ...
    def __getitem__(self, key: tuple[Node, builtins.str]) -> builtins.float:
        r"""
        `field[node, "UX"]` — raises IndexError if absent.
        """
    def __setitem__(self, key: tuple[Node, builtins.str], value: builtins.float) -> None:
        r"""
        `field[node, "UX"] = v` — raises IndexError if absent.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> builtins.str:
        r"""
        Full content (third display level): values / topology, beyond
        `repr`'s bounded structure.
        """

@typing.final
class SubElementField:
    r"""
    A **view** into one zone of an `ElementField`, obtained by indexing
    (`element_field[i]`) — never constructed directly. Build at the parent
    level instead: `ElementField(fes, components)` or
    `material_field(model, ...)`, composed with `+`.
    """
    def cell_count(self) -> builtins.int:
        r"""
        Number of cells (elements) this field covers.
        """
    def gauss_count(self) -> builtins.int:
        r"""
        Number of Gauss points per cell.
        """
    def component_count(self) -> builtins.int:
        r"""
        Number of components stored per point.
        """
    def components(self) -> builtins.list[builtins.str]:
        r"""
        Component names, in order.
        """
    def component_index(self, name: builtins.str) -> typing.Optional[builtins.int]:
        r"""
        Index of component `name`, or `None` if unknown.
        """
    def get(self, cell: builtins.int, gauss: builtins.int, comp: builtins.int) -> builtins.float:
        r"""
        Value at `(cell, gauss)` for component index `comp`.
        """
    def set(self, cell: builtins.int, gauss: builtins.int, comp: builtins.int, value: builtins.float) -> None:
        r"""
        Set the value at `(cell, gauss)` for component index `comp`.
        """
    def value(self, cell: builtins.int, gauss: builtins.int, component: builtins.str) -> builtins.float:
        r"""
        Value at `(cell, gauss)` for the named `component`.
        """
    def set_value(self, cell: builtins.int, gauss: builtins.int, component: builtins.str, value: builtins.float) -> None:
        r"""
        Set the value at `(cell, gauss)` for the named `component`.
        """
    def point_values(self, cell: builtins.int, gauss: builtins.int) -> builtins.list[builtins.float]:
        r"""
        All component values at `(cell, gauss)`, in component order.
        """
    def set_uniform(self, component: builtins.str, value: builtins.float) -> None:
        r"""
        Set `component` to `value` at every point.
        """
    def set_cell_uniform(self, cell: builtins.int, component: builtins.str, value: builtins.float) -> None:
        r"""
        Set `component` to `value` at every point of `cell`.
        """
    def add_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Add `scalar` to every value of `component` (in place).
        """
    def sub_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Subtract `scalar` from every value of `component` (in place).
        """
    def mul_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Multiply every value of `component` by `scalar` (in place).
        """
    def div_to_component(self, component: builtins.str, scalar: builtins.float) -> None:
        r"""
        Divide every value of `component` by `scalar` (in place).
        """
    def __add__(self, rhs: builtins.float) -> SubElementField: ...
    def __sub__(self, rhs: builtins.float) -> SubElementField: ...
    def __mul__(self, rhs: builtins.float) -> SubElementField: ...
    def __truediv__(self, rhs: builtins.float) -> SubElementField: ...
    def __getitem__(self, key: tuple[builtins.int, builtins.int, builtins.str]) -> builtins.float:
        r"""
        `field[cell, gauss, "name"]` — raises ValueError if the component
        is unknown.
        """
    def __setitem__(self, key: tuple[builtins.int, builtins.int, builtins.str], value: builtins.float) -> None:
        r"""
        `field[cell, gauss, "name"] = value`.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> builtins.str:
        r"""
        Full content (third display level): values / topology, beyond
        `repr`'s bounded structure.
        """

@typing.final
class SubFiniteElementSpace:
    r"""
    One subspace of a `FiniteElementSpace`: the finite elements over a
    single submesh, with their interpolation and quadrature.
    
    A read-only view obtained by indexing the parent (`fes[i]`); index it
    further (`fes[i][j]`) to reach an `Element`. Not constructed directly.
    """
    @property
    def element_type(self) -> builtins.str:
        r"""
        Element type name (e.g. `"TRI3"`).
        """
    @property
    def interpolation(self) -> builtins.str:
        r"""
        Interpolation name (e.g. `"LAGRANGE1"`).
        """
    @property
    def quadrature(self) -> builtins.str:
        r"""
        Quadrature-rule name (e.g. `"GAUSS"`).
        """
    @property
    def ref_dim(self) -> builtins.int:
        r"""
        Reference (parametric) dimension of the elements.
        """
    @property
    def space_dim(self) -> builtins.int:
        r"""
        Spatial dimension the elements live in.
        """
    @property
    def nodes_per_cell(self) -> builtins.int:
        r"""
        Number of nodes per element.
        """
    def cell_count(self) -> builtins.int:
        r"""
        Number of elements (cells) in this subspace.
        """
    def gauss_count(self) -> builtins.int:
        r"""
        Number of Gauss (quadrature) points per element.
        """
    def gauss_xi(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Reference coordinates of the `g`-th Gauss point.
        """
    def gauss_weight(self, g: builtins.int) -> builtins.float:
        r"""
        Weight of the `g`-th Gauss point.
        """
    def n_at_g(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        `N_i(ξ_g)` at the `g`-th Gauss point (flat, length `nodes_per_cell`).
        """
    def dn_at_g(self, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        `∂N_i/∂ξ_j(ξ_g)` at the `g`-th Gauss point.
        
        Flat row-major: index `[i * ref_dim + j]`.
        """
    def jacobian(self, cell_idx: builtins.int, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Jacobian `J = ∂x/∂ξ` of cell `cell_idx` at Gauss point `g`.
        
        Flat row-major buffer of length `space_dim × ref_dim`,
        indexed `[a * ref_dim + k]`.
        """
    def det_jacobian(self, cell_idx: builtins.int, g: builtins.int) -> builtins.float:
        r"""
        `|J|` — `|det(J)|` if `space_dim == ref_dim`, else
        `sqrt(det(JᵀJ))`. Always non-negative.
        """
    def dn_dx(self, cell_idx: builtins.int, g: builtins.int) -> builtins.list[builtins.float]:
        r"""
        Physical derivatives `∂N_i/∂x_a` of cell `cell_idx` at Gauss
        point `g`. Flat row-major buffer of length
        `nodes_per_cell × space_dim`, indexed `[i * space_dim + a]`.
        """
    def element(self, i: builtins.int) -> Element:
        r"""
        Element view on the `i`-th cell of this subspace.
        """
    def elements(self) -> builtins.list[Element]:
        r"""
        All elements as a Python list.
        """
    def __len__(self) -> builtins.int:
        r"""
        `len(subspace)` → number of elements (= number of cells).
        """
    def __getitem__(self, idx: builtins.int) -> Element:
        r"""
        `subspace[i]` → `Element` view on element `i`. Supports negative
        indices and raises `IndexError` out of range so
        `for el in subspace:` works.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> builtins.str:
        r"""
        Full content (third display level): values / topology, beyond
        `repr`'s bounded structure.
        """

@typing.final
class SubMatrix:
    r"""
    One block (a COO sub-matrix) of a global `Matrix`, viewed by indexing
    (`matrix[i]`) — never constructed directly. Build a block at the parent
    level with `Matrix.block(...)` (a unit `Matrix`), composed with `+`.
    """
    @property
    def symmetric(self) -> builtins.bool:
        r"""
        Whether this block is declared symmetric.
        """
    def add_entry(self, row_node: Node, row_field: builtins.str, col_node: Node, col_field: builtins.str, value: builtins.float) -> None:
        r"""
        Accumulate `value` at row `(row_node, row_field)`, column
        `(col_node, col_field)` (COO entry).
        """
    def get(self, row_node: Node, row_field: builtins.str, col_node: Node, col_field: builtins.str) -> builtins.float:
        r"""
        Value at row `(row_node, row_field)`, column `(col_node, col_field)`.
        """
    def n_rows(self) -> builtins.int:
        r"""
        Number of rows of this block.
        """
    def n_cols(self) -> builtins.int:
        r"""
        Number of columns of this block.
        """
    def entry_count(self) -> builtins.int:
        r"""
        Number of stored COO entries.
        """
    def field_names(self) -> builtins.list[builtins.str]:
        r"""
        Variable (field) names this block addresses.
        """
    def row_dofs(self) -> builtins.list[tuple[builtins.int, builtins.str]]:
        r"""
        `(node_id, field_name)` tuples for each row, in order.
        """
    def col_dofs(self) -> builtins.list[tuple[builtins.int, builtins.str]]:
        r"""
        `(node_id, field_name)` tuples for each column, in order.
        """
    def dense(self) -> builtins.list[builtins.float]:
        r"""
        Dense row-major buffer, length `n_rows × n_cols`.
        """
    def mul_dense(self, x: typing.Sequence[builtins.float]) -> builtins.list[builtins.float]:
        r"""
        `y = A · x` (dense).
        """
    def entries(self) -> builtins.list[tuple[builtins.int, builtins.str, builtins.int, builtins.str, builtins.float]]:
        r"""
        List of `(row_node, row_field, col_node, col_field, value)`
        tuples, in insertion order.
        """
    def __len__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> builtins.str:
        r"""
        Full content (third display level): values / topology, beyond
        `repr`'s bounded structure.
        """

@typing.final
class SubMesh:
    r"""
    A **view** into one submesh of a `Mesh` — the cells of a single element
    type. Obtained by indexing (`mesh[i]`); never constructed directly.
    Build at the parent level instead: `Mesh(config, element_type)` for a
    single zone, composed with `+` for several.
    """
    @property
    def element_type(self) -> builtins.str:
        r"""
        Element type name of this submesh (e.g. `"TRI3"`).
        """
    @property
    def face_color(self) -> tuple[builtins.int, builtins.int, builtins.int]:
        r"""
        Face colour as an `(r, g, b)` tuple of bytes.
        """
    @face_color.setter
    def face_color(self, value: tuple[builtins.int, builtins.int, builtins.int]) -> None:
        r"""
        Set the face colour from an `(r, g, b)` tuple of bytes.
        """
    def add_cell(self, nodes: typing.Sequence[Node]) -> builtins.int:
        r"""
        Append a cell from its list of nodes; returns the new cell's index.
        """
    def cell_count(self) -> builtins.int:
        r"""
        Number of cells in this submesh.
        """
    def plot(self, view: typing.Optional[tuple[builtins.float, builtins.float, builtins.float]] = None, save: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, show_axes: builtins.bool = True, field: typing.Optional[NodeField] = None, component: typing.Optional[builtins.str] = None, vmin: typing.Optional[builtins.float] = None, vmax: typing.Optional[builtins.float] = None, cmap: typing.Optional[builtins.str] = None) -> None:
        r"""
        Visualize this submesh.
        
        - `save=None`: interactive window (requires `viz-interactive`).
        - `save="<path>.png"` or `.svg`: image file.
        - `view`: optional `(yaw, pitch, scale)` triple; default is iso.
        - `show_axes`: draw the X/Y/Z orientation gizmo in the bottom-left
          corner (default `True`). In the interactive window, the key
          `A` toggles it at runtime.
        - `field`: optional `NodeField` whose values colour each cell
          (per-cell value = mean over the cell's nodes of the chosen
          component). Default `None` ⇒ uniform face colour.
        - `component`: component name to display when `field` is set
          (defaults to the field's first component). In the
          interactive window, click the top button or press `Tab` to
          cycle through every component.
        - `vmin` / `vmax`: pin the bottom / top of the colour scale (and
          of the colorbar drawn on the right). Either may be left `None`
          to track the data's own min / max for that bound.
        - `cmap`: colour scale name — `"viridis"` (default), `"jet"`,
          `"coolwarm"`, `"hot"` or `"gray"`.
        """
    def __len__(self) -> builtins.int:
        r"""
        `len(submesh)` → number of cells.
        """
    def __getitem__(self, idx: builtins.int) -> Cell:
        r"""
        `submesh[i]` → `Cell` view on cell i. Supports negative
        indices and raises `IndexError` out of range so
        `for cell in submesh:` works.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> builtins.str:
        r"""
        Full content (third display level): values / topology, beyond
        `repr`'s bounded structure.
        """

@typing.final
class SubModel:
    r"""
    A **view** into one sub-model of a `Model`, obtained by indexing
    (`model[i]`) — never constructed directly. Build physics at the parent
    level instead: `Model.heat_conduction(fes)` or `Model.dirichlet(...)`,
    composed with `+`.
    """
    def primal_vars(self) -> builtins.list[builtins.str]:
        r"""
        Names of the primal (primary) variables of this sub-model.
        """
    def dual_vars(self) -> builtins.list[builtins.str]:
        r"""
        Names of the dual variables of this sub-model.
        """
    def multiplier_mesh(self) -> Mesh:
        r"""
        POI1 `Mesh` of the multiplier nodes (Lagrange physics only — empty
        otherwise). Build a load `NodeField` on `mesh[0]` to impose the
        constrained values, or read the nodes via `mesh.node(0, i, 0)`.
        """
    def material_components(self) -> typing.Optional[builtins.list[builtins.str]]:
        r"""
        Names of the material components this sub-model expects, or
        `None` for physics that don't need material data (Dirichlet, …).
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dump(self, precision: builtins.int = 3, max_rows: builtins.int = 20, max_cols: builtins.int = 12) -> builtins.str:
        r"""
        Full content (third display level): values / topology, beyond
        `repr`'s bounded structure.
        """

def circle_seg2(center: Node, normal: typing.Sequence[builtins.float], radius: builtins.float, n_elems: builtins.int) -> Mesh:
    r"""
    Build a closed circle of `n_elems` SEG2 elements, centred on `center`
    in the plane defined by `normal`, with the given `radius`.
    """

def consolidate(mesh: Mesh) -> Mesh:
    r"""
    Fuse submeshes of the same element type into one and drop duplicate
    cells. Returns a new mesh with one submesh per element type, in
    first-seen order.
    """

def coordinates(mesh: Mesh, components: typing.Optional[typing.Sequence[builtins.str]] = None) -> NodeField:
    r"""
    Build a `NodeField` carrying the coordinates of every node of `mesh`.
    
    One component per requested axis (`"X"`, `"Y"`, `"Z"`). `components=None`
    requests all the axes the mesh's `Configuration` has (`["X"]` in 1-D,
    `["X", "Y"]` in 2-D, `["X", "Y", "Z"]` in 3-D). A non-POI1 mesh is
    converted to POI1 internally (see `to_poi1`); the support is the unique
    nodes of the mesh, in order of first appearance.
    """

def extrude(mesh: Mesh, direction: typing.Sequence[builtins.float], n_layers: builtins.int) -> Mesh:
    r"""
    Extrude `mesh` by `n_layers` layers along `direction` (the total
    displacement vector). SEG2 → QUA4, QUA4 → HEX8.
    """

def fill_surface(contour: Mesh, element_type: builtins.str, max_edge_length: typing.Optional[builtins.float] = None, min_angle_deg: typing.Optional[builtins.float] = None) -> Mesh:
    r"""
    Fill the interior of a closed SEG2 `contour` with `element_type` cells
    (triangulation). `max_edge_length` / `min_angle_deg` optionally refine
    the result.
    """

def from_live_nodes(config: Configuration) -> Mesh:
    r"""
    Build a points (POI1) mesh holding every live node of `config`.
    """

def line_seg2(a: Node, b: Node, n_elems: builtins.int) -> Mesh:
    r"""
    Build a line of `n_elems` SEG2 elements from node `a` to node `b`.
    """

def mass(model: Model) -> Matrix:
    r"""
    Assemble the mass matrix `M` of `model`.
    
    v0 stub: no physics has a mass term yet, so this returns an empty
    finalized `Matrix` with the model's DOF layout.
    """

def material_field(model: Model, components_and_values: typing.Sequence[tuple[builtins.str, builtins.float]]) -> ElementField:
    r"""
    Build a material `ElementField` applying the same uniform
    `(component, value)` pairs to every material-hungry sub-model of
    `model`. Sub-models that need no material (Dirichlet, …) are skipped.
    """

def material_field_per_sub_model(model: Model, components_and_values_per_sub_model: typing.Sequence[typing.Sequence[tuple[builtins.str, builtins.float]]]) -> ElementField:
    r"""
    Build a material `ElementField` where each sub-model gets its own
    `(component, value)` list. The outer list length must equal
    `model.sub_model_count()`. An empty inner list **skips** the matching
    sub-model (typical for Dirichlet).
    """

def merge(a: NodeField, b: NodeField) -> NodeField:
    r"""
    Merge two node fields over the union of their supports.
    
    Keeps each field's value where only one is defined, `0.0` where
    neither is. Errors if the two fields hold different values at the same
    `(node, component)` pair, or are attached to different `Configuration`s.
    """

def restrict(field: NodeField, mesh: Mesh) -> NodeField:
    r"""
    Restrict `field` to the nodes used by `mesh`.
    
    Returns a new `NodeField` with the same components, supported on the
    unique nodes of `mesh` (order of first appearance). Nodes of `mesh`
    absent from `field` are assigned `0.0`. Errors if `mesh` and `field`
    are attached to different `Configuration`s.
    """

def set_swap_dir(path: builtins.str | os.PathLike | pathlib.Path) -> None:
    r"""
    Set the directory used to swap large objects to disk. If never set, a
    per-process subdirectory of the system temp dir is used.
    """

def solve(matrix: Matrix, rhs: NodeField) -> NodeField:
    r"""
    Solve the linear system `A·x = b` for `x` (dense LU).
    
    `matrix` is the finalized system `A`; `rhs` is the right-hand side `b`
    as a `NodeField`. Returns the solution `x` as a `NodeField` over the
    same support.
    """

def stiffness(model: Model, materials: ElementField) -> Matrix:
    r"""
    Assemble the stiffness matrix `K` of `model`.
    
    `materials` carries the per-zone material data: every sub-model that
    needs it picks the `SubElementField` whose FE subspace matches its own.
    """

def sub_material_field(sub_model: SubModel, components_and_values: typing.Sequence[tuple[builtins.str, builtins.float]]) -> SubElementField:
    r"""
    Build the material `SubElementField` of one sub-model.
    
    `sub_material_field(sub_model, [("k", 1.0), ...])` — fresh
    SubElementField on the sub-model's FE subspace, pre-filled with the
    given uniform value per declared component. Errors for physics that
    need no material (e.g. Dirichlet).
    """

def swap_dir() -> pathlib.Path:
    r"""
    Return the effective swap directory (creating it if necessary).
    """

def sweep_qua4(mesh_a: Mesh, mesh_b: Mesh, n_layers: builtins.int) -> Mesh:
    r"""
    Sweep two SEG2 line meshes into a QUA4 mesh, building `n_layers` layers
    of quads between `mesh_a` and `mesh_b`.
    """

def to_poi1(mesh: Mesh) -> Mesh:
    r"""
    Convert a mesh to POI1, submesh by submesh.
    
    Returns a new mesh with the same number of submeshes; each output
    submesh is a POI1 submesh holding the de-duplicated nodes of the
    corresponding input submesh, in order of first appearance.
    """

