"""Opérateurs produisant un maillage — miroir de ``ops::mesh`` (Rust).

Mailleurs (ligne, cercle, arc, transfini, pavage, triangulation), balayages
et transformations, extraction de peau et de bord, sélections géométriques,
lecture gmsh. Tout ce qui rend un ``Mesh`` est ici, quelle que soit l'entrée
— y compris ``select``, qui extrait le support d'un champ.
"""

from ._pyrucast import (
    arc as arc,
    barycenter as barycenter,
    border as border,
    chain as chain,
    circle as circle,
    consolidate_mesh as consolidate,
    convert as convert,
    elements_on as elements_on,
    extrude as extrude,
    from_live_nodes as from_live_nodes,
    invert as invert,
    line as line,
    merge_nodes as merge_nodes,
    orient as orient,
    pave_surface as pave_surface,
    pave_volume as pave_volume,
    points_below_plane as points_below_plane,
    points_in_cone as points_in_cone,
    points_in_cylinder as points_in_cylinder,
    points_in_sphere as points_in_sphere,
    points_in_torus as points_in_torus,
    points_on_cone as points_on_cone,
    points_on_cylinder as points_on_cylinder,
    points_on_line as points_on_line,
    points_on_plane as points_on_plane,
    points_on_sphere as points_on_sphere,
    points_on_torus as points_on_torus,
    read_gmsh as read_gmsh,
    read_gmsh_str as read_gmsh_str,
    revolve as revolve,
    rotate as rotate,
    select as select,
    skin as skin,
    sweep as sweep,
    sweep_solid as sweep_solid,
    symmetry_line as symmetry_line,
    symmetry_plane as symmetry_plane,
    symmetry_point as symmetry_point,
    to_poi1 as to_poi1,
    to_quadratic as to_quadratic,
    transfinite as transfinite,
    translate as translate,
    triangulate_surface as triangulate_surface,
    triangulate_volume as triangulate_volume,
)

__all__ = [
    "arc",
    "barycenter",
    "border",
    "chain",
    "circle",
    "consolidate",
    "convert",
    "elements_on",
    "extrude",
    "from_live_nodes",
    "invert",
    "line",
    "merge_nodes",
    "orient",
    "pave_surface",
    "pave_volume",
    "points_below_plane",
    "points_in_cone",
    "points_in_cylinder",
    "points_in_sphere",
    "points_in_torus",
    "points_on_cone",
    "points_on_cylinder",
    "points_on_line",
    "points_on_plane",
    "points_on_sphere",
    "points_on_torus",
    "read_gmsh",
    "read_gmsh_str",
    "revolve",
    "rotate",
    "select",
    "skin",
    "sweep",
    "sweep_solid",
    "symmetry_line",
    "symmetry_plane",
    "symmetry_point",
    "to_poi1",
    "to_quadratic",
    "transfinite",
    "translate",
    "triangulate_surface",
    "triangulate_volume",
]
