"""Operators producing a mesh — mirror of ``ops::mesh`` (Rust).

Meshers (line, circle, arc, transfinite, paving, triangulation), sweeps and
transformations, skin and border extraction, geometric selections, gmsh
reading. Everything that returns a ``Mesh`` is here, whatever the input —
including ``select``, which extracts a field's support.

``from_gmsh`` and ``from_medcoupling`` are the only functions of this module
written in Python: they need an interpreter carrying the ``gmsh`` or
``medcoupling`` module, which Rust cannot have — and they import it only when
called, never at ``import pyrucast``. They merely fetch the arrays of a live
gmsh model or of a MED file and hand them to ``from_arrays``, the Rust import
every exchange format shares.
"""

from ._pyrucast import (
    arc as arc,
    barycenter as barycenter,
    border as border,
    chain as chain,
    cleanup as cleanup,
    circle as circle,
    consolidate_mesh as consolidate,
    convert as convert,
    copy as copy,
    elements_on as elements_on,
    extrude as extrude,
    from_arrays as from_arrays,
    element_type_from_gmsh as element_type_from_gmsh,
    gauss_to_external as gauss_to_external,
    match_gauss as match_gauss,
    from_live_nodes as from_live_nodes,
    grid_surface as grid_surface,
    grid_surface2 as grid_surface2,
    invert as invert,
    line as line,
    merge_triangles as merge_triangles,
    merge_nodes as merge_nodes,
    orient as orient,
    pave_surface as pave_surface,
    pave_volume as pave_volume,
    poi1_from_nodes as poi1_from_nodes,
    points_below_plane as points_below_plane,
    points_in_cone as points_in_cone,
    points_in_cylinder as points_in_cylinder,
    points_in_sphere as points_in_sphere,
    points_in_torus as points_in_torus,
    points_on_cone as points_on_cone,
    points_on_cylinder as points_on_cylinder,
    points_on_line as points_on_line,
    points_on_plane as points_on_plane,
    points_on_sphere as points_on_sphere,
    points_on_torus as points_on_torus,
    read_gmsh as read_gmsh,
    regularize as regularize,
    read_gmsh_str as read_gmsh_str,
    revolve as revolve,
    rotate as rotate,
    select as select,
    skin as skin,
    sweep as sweep,
    sweep_solid as sweep_solid,
    symmetry_line as symmetry_line,
    symmetry_plane as symmetry_plane,
    symmetry_point as symmetry_point,
    to_poi1 as to_poi1,
    to_quadratic as to_quadratic,
    transfinite as transfinite,
    translate as translate,
    triangulate_surface as triangulate_surface,
    triangulate_volume as triangulate_volume,
)

__all__ = [
    "arc",
    "barycenter",
    "border",
    "chain",
    "circle",
    "cleanup",
    "consolidate",
    "convert",
    "element_type_from_gmsh",
    "elements_on",
    "extrude",
    "from_arrays",
    "from_gmsh",
    "from_live_nodes",
    "from_medcoupling",
    "gauss_to_external",
    "grid_surface",
    "grid_surface2",
    "invert",
    "line",
    "match_gauss",
    "merge_nodes",
    "merge_triangles",
    "orient",
    "pave_surface",
    "pave_volume",
    "poi1_from_nodes",
    "points_below_plane",
    "points_in_cone",
    "points_in_cylinder",
    "points_in_sphere",
    "points_in_torus",
    "points_on_cone",
    "points_on_cylinder",
    "points_on_line",
    "points_on_plane",
    "points_on_sphere",
    "points_on_torus",
    "read_gmsh",
    "read_gmsh_str",
    "regularize",
    "revolve",
    "rotate",
    "select",
    "skin",
    "sweep",
    "sweep_solid",
    "symmetry_line",
    "symmetry_plane",
    "symmetry_point",
    "to_poi1",
    "to_quadratic",
    "transfinite",
    "translate",
    "triangulate_surface",
    "triangulate_volume",
]


# Exchange adapters written in Python: they need an interpreter carrying the
# `gmsh` / `medcoupling` modules, imported only when one of them runs.
from ._gmsh import from_gmsh as from_gmsh  # noqa: E402
from ._med import from_medcoupling as from_medcoupling  # noqa: E402
