[book]
title = "pyrucast — documentation théorique"
authors = ["pyrucast"]
language = "fr"
src = "src"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
